In [1]:
import numpy as np
import pandas as pd

In [2]:
fact_disease_incident = pd.read_csv('Fact_Disease_Incidents.csv')
patient = pd.read_csv('Dim_Patient.csv')
location = pd.read_csv('Dim_Location.csv')
hospital = pd.read_csv('Dim_Hospital.csv')
disease = pd.read_csv('Dim_Disease.csv')
date = pd.read_csv('Dim_Date.csv')

In [3]:
fact_disease_incident.head()

,incident_id,date_id,patient_id,disease_id,location_id,hospital_id,admission_type,length_of_stay_days,treatment_cost_usd,insurance_claim_amount_usd,outcome,follow_up_required,readmission_flag,symptom_severity_score
0,INC0254876,20240126,PAT004852,DIS049,LOC0058,HOS0189,Outpatient,8.0,2362.43,1255.48,Recovered,Yes,No,10.0
1,INC0191764,20230730,PAT024263,DIS003,LOC0003,HOS0152,Elective,7.0,4822.12,3582.07,Recovered,Yes,No,7.0
2,INC0153710,20241111,PAT037790,DIS047,LOC0020,HOS0045,Emergency,18.0,4012.48,2185.31,ONGOING TREATMENT,Yes,No,3.0
3,INC0198303,20230703,PAT003461,DIS021,LOC0037,HOS0279,Urgent,14.0,8837.01,7034.78,Recovered,Yes,No,8.0
4,INC0221027,20240620,PAT018040,DIS016,LOC0042,HOS0113,Elective,7.0,1056.38,511.05,Recovered,No,No,2.0

In [4]:
patient.head()

,patient_id,first_name,last_name,gender,date_of_birth,age,blood_group,ethnicity,marital_status,occupation,insurance_type,smoking_status,income_bracket
0,PAT016319,Alicia,Gomez,Female,1978-03-28,46,B+,Pacific Islander,Divorced,Software Developer,Employer-Sponsored,Never Smoked,"$25,000-$49,999"
1,PAT011155,Stacy,nguyen,Female,2000-12-30,24,AB-,Hispanic or Latino,Widowed,Artist,Medicaid,Current Smoker,"Under $25,000"
2,PAT026587,Michael,MCKINNEY,Male,1944-11-15,80,O+,Native American,Divorced,Driver,Medicaid,Current Smoker,"$75,000-$99,999"
3,PAT030794,Carol,Martin,Female,1959-11-01,65,AB+,TWO OR MORE RACES,Single,SOFTWARE DEVELOPER,Medicare,Current Smoker,"$100,000-$149,999"
4,PAT016673,Victoria,Jones,Other,1958-01-06,67,O+,Black or African American,Married,Electrician,NaN,Current Smoker,"$75,000-$99,999"

In [5]:
location.head()

,location_id,city,state,region,country,zip_code,population_density_per_sqkm
0,LOC0069,Little Rock,AR,South,USA,6507.0,10197.0
1,LOC0059,richmond,VA,South,USA,10829.0,7091.0
2,LOC0073,Charleston,SC,South,USA,10959.0,3123.0
3,LOC0010,Dallas,TX,south,USA,13935.0,5628.0
4,LOC0071,Anchorage,AK,West,USA,30372.0,3993.0

In [6]:
hospital.head()

,hospital_id,hospital_name,hospital_type,ownership_type,city,state,bed_capacity,accreditation_status,established_year
0,HOS0064,jackson university hospital,general hospital,Private,Jackson,MS,250.0,NaN,1928
1,HOS0035,Virginia Beach Medical Center #035,Community Hospital,Non-Profit,Virginia Beach,VA,NaN,Not Accredited,1974
2,HOS0186,Savannah Community Health Center #186,General Hospital,University-Affiliated,Savannah,GA,200.0,NABH Accredited,1935
3,HOS0147,Tulsa Health System,General Hospital,Non-Profit,Tulsa,OK,NaN,NaN,1984
4,HOS0131,Charlotte General Hospital #131,Children's Hospital,Government,CHARLOTTE,NC,300.0,Not Accredited,1997

In [7]:
disease.head()

,disease_id,disease_name,disease_category,icd10_code,chronic_flag,transmission_type,severity_level,avg_recovery_days
0,DIS039,Colorectal Cancer,Oncology,C18,Yes,Non-communicable,Severe,NaN
1,DIS038,lung cancer,Oncology,C34,Yes,Non-communicable,Chronic-Managed,NaN
2,DIS033,Alzheimer's Disease,Neurological,G30,Yes,Non-communicable,Severe,NaN
3,DIS045,Psoriasis,Dermatological,L40,Yes,Non-communicable,Moderate,NaN
4,DIS049,Irritable Bowel Syndrome,Digestive,K58,Yes,Non-communicable,NaN,NaN

In [8]:
date.head()

,date_id,full_date,day,month,month_name,quarter,year,day_of_week,is_weekend,fiscal_year
0,20221017,2022-10-17,17.0,10,October,Q4,2022,Monday,False,FY2023
1,20230130,2023-01-30,30.0,1,January,Q1,2023,Monday,False,fy2023
2,20241107,2024-11-07,7.0,11,november,q4,2024,Thursday,False,FY2025
3,20230816,2023-08-16,16.0,8,August,Q3,2023,Wednesday,False,FY2024
4,20220329,2022-03-29,29.0,3,March,Q1,2022,Tuesday,False,FY2022

## 1. Data Exploration - EDA

In [9]:
fact_disease_incident.head()

,incident_id,date_id,patient_id,disease_id,location_id,hospital_id,admission_type,length_of_stay_days,treatment_cost_usd,insurance_claim_amount_usd,outcome,follow_up_required,readmission_flag,symptom_severity_score
0,INC0254876,20240126,PAT004852,DIS049,LOC0058,HOS0189,Outpatient,8.0,2362.43,1255.48,Recovered,Yes,No,10.0
1,INC0191764,20230730,PAT024263,DIS003,LOC0003,HOS0152,Elective,7.0,4822.12,3582.07,Recovered,Yes,No,7.0
2,INC0153710,20241111,PAT037790,DIS047,LOC0020,HOS0045,Emergency,18.0,4012.48,2185.31,ONGOING TREATMENT,Yes,No,3.0
3,INC0198303,20230703,PAT003461,DIS021,LOC0037,HOS0279,Urgent,14.0,8837.01,7034.78,Recovered,Yes,No,8.0
4,INC0221027,20240620,PAT018040,DIS016,LOC0042,HOS0113,Elective,7.0,1056.38,511.05,Recovered,No,No,2.0

In [10]:
fact_disease_incident.tail()

,incident_id,date_id,patient_id,disease_id,location_id,hospital_id,admission_type,length_of_stay_days,treatment_cost_usd,insurance_claim_amount_usd,outcome,follow_up_required,readmission_flag,symptom_severity_score
365795,INC0195950,20240305,PAT027168,DIS049,LOC0014,HOS0114,Elective,10.0,2174.63,NaN,Recovered,no,No,10.0
365796,INC0266859,20210824,PAT021755,DIS035,LOC0010,HOS0158,Emergency,6.0,2161.31,983.12,Recovered,No,NaN,NaN
365797,INC0239573,20230225,PAT035456,DIS002,LOC0003,HOS0269,Elective,19.0,6307.34,3571.64,DISCHARGED AGAINST MEDICAL ADVICE,Yes,No,6.0
365798,INC0303332,20210922,PAT018468,DIS043,LOC0072,HOS0268,Emergency,NaN,5196.33,2290.55,Referred,No,Yes,9.0
365799,INC0162699,20210214,PAT010204,DIS043,LOC0048,HOS0071,Emergency,7.0,4510.58,NaN,NaN,Yes,Yes,10.0

In [11]:
fact_disease_incident.shape # 365800 rows and 14 columns

(365800, 14)

In [12]:
fact_disease_incident.columns

Index(['incident_id', 'date_id', 'patient_id', 'disease_id', 'location_id',
       'hospital_id', 'admission_type', 'length_of_stay_days',
       'treatment_cost_usd', 'insurance_claim_amount_usd', 'outcome',
       'follow_up_required', 'readmission_flag', 'symptom_severity_score'],
      dtype='object')

In [13]:
fact_disease_incident.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365800 entries, 0 to 365799
Data columns (total 14 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   incident_id                 365800 non-null  object
 1   date_id                     365800 non-null  int64
 2   patient_id                  365800 non-null  object
 3   disease_id                  365800 non-null  object
 4   location_id                 365800 non-null  object
 5   hospital_id                 365800 non-null  object
 6   admission_type              336600 non-null  object
 7   length_of_stay_days         336584 non-null  float64
 8   treatment_cost_usd          329203 non-null  float64
 9   insurance_claim_amount_usd  329026 non-null  float64
 10  outcome                     336564 non-null  object
 11  follow_up_required          336615 non-null  object
 12  readmission_flag            336443 non-null  object
 13  symptom_severity_score      343859 non-null  float64
dtypes: float64(4), int64(1), object(9)
memory usage: 39.1+ MB

> Length of stay days and symptom severity score - int64

In [14]:
fact_disease_incident.describe()

,date_id,length_of_stay_days,treatment_cost_usd,insurance_claim_amount_usd,symptom_severity_score
count,3.658000e+05,336584.000000,329203.000000,329026.000000,343859.000000
mean,2.022567e+07,9.983855,4103.224834,2768.264926,5.507758
std,1.118089e+04,7.414707,2660.133892,1953.895478,2.868053
min,2.021010e+07,0.000000,152.320000,69.820000,1.000000
25%,2.022010e+07,4.000000,2141.960000,1361.200000,3.000000
50%,2.023010e+07,9.000000,3528.930000,2295.440000,5.000000
75%,2.023123e+07,15.000000,5438.250000,3661.125000,8.000000
max,2.024123e+07,30.000000,29283.030000,24377.480000,10.000000

In [15]:
fact_disease_incident.isna().sum()

incident_id                       0
date_id                           0
patient_id                        0
disease_id                        0
location_id                       0
hospital_id                       0
admission_type                29200
length_of_stay_days           29216
treatment_cost_usd            36597
insurance_claim_amount_usd    36774
outcome                       29236
follow_up_required            29185
readmission_flag              29357
symptom_severity_score        21941
dtype: int64

> Null values exists

In [16]:
fact_disease_incident.duplicated().sum()

np.int64(55800)

In [17]:
fact_disease_incident['incident_id'].duplicated().sum()

np.int64(55800)

In [18]:
fact_disease_incident[fact_disease_incident['incident_id'].duplicated(keep=False)].sort_values('incident_id')

,incident_id,date_id,patient_id,disease_id,location_id,hospital_id,admission_type,length_of_stay_days,treatment_cost_usd,insurance_claim_amount_usd,outcome,follow_up_required,readmission_flag,symptom_severity_score
200523,INC0000005,20230606,PAT015367,DIS043,LOC0035,HOS0191,Elective,3.0,5125.86,3972.54,Recovered,Yes,NaN,3.0
189332,INC0000005,20230606,PAT015367,DIS043,LOC0035,HOS0191,Elective,3.0,5125.86,3972.54,Recovered,Yes,NaN,3.0
5550,INC0000011,20220223,PAT007600,DIS003,LOC0070,HOS0043,Outpatient,9.0,7088.40,3678.06,Referred,No,Yes,3.0
285422,INC0000011,20220223,PAT007600,DIS003,LOC0070,HOS0043,Outpatient,9.0,7088.40,3678.06,Referred,No,Yes,3.0
37833,INC0000013,20210505,PAT024904,DIS034,LOC0064,HOS0242,Urgent,18.0,4498.78,3547.92,Ongoing Treatment,Yes,NaN,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315753,INC0309978,20220421,PAT028747,DIS043,LOC0072,HOS0228,Emergency,3.0,3691.81,NaN,Recovered,Yes,No,3.0
132383,INC0309981,20230530,PAT013449,DIS029,LOC0067,HOS0187,Newborn,NaN,11682.65,4706.31,Recovered,Yes,No,10.0
304517,INC0309981,20230530,PAT013449,DIS029,LOC0067,HOS0187,Newborn,NaN,11682.65,4706.31,Recovered,Yes,No,10.0
16420,INC0309993,20220304,PAT005200,DIS026,LOC0053,HOS0229,Emergency,2.0,925.03,817.04,Recovered,NaN,No,5.0
165129,INC0309993,20220304,PAT005200,DIS026,LOC0053,HOS0229,Emergency,2.0,925.03,817.04,Recovered,NaN,No,5.0

> Duplicates needs to be removed

In [19]:
Missing_Summary = pd.DataFrame({'Missing count':fact_disease_incident.isnull().sum(),'Missing %': fact_disease_incident.isnull().mean()*100}).round(2)
Missing_Summary

                            Missing count  Missing %
incident_id                             0       0.00
date_id                                 0       0.00
patient_id                              0       0.00
disease_id                              0       0.00
location_id                             0       0.00
hospital_id                             0       0.00
admission_type                      29200       7.98
length_of_stay_days                 29216       7.99
treatment_cost_usd                  36597      10.00
insurance_claim_amount_usd          36774      10.05
outcome                             29236       7.99
follow_up_required                  29185       7.98
readmission_flag                    29357       8.03
symptom_severity_score              21941       6.00

In [20]:
patient.head()

,patient_id,first_name,last_name,gender,date_of_birth,age,blood_group,ethnicity,marital_status,occupation,insurance_type,smoking_status,income_bracket
0,PAT016319,Alicia,Gomez,Female,1978-03-28,46,B+,Pacific Islander,Divorced,Software Developer,Employer-Sponsored,Never Smoked,"$25,000-$49,999"
1,PAT011155,Stacy,nguyen,Female,2000-12-30,24,AB-,Hispanic or Latino,Widowed,Artist,Medicaid,Current Smoker,"Under $25,000"
2,PAT026587,Michael,MCKINNEY,Male,1944-11-15,80,O+,Native American,Divorced,Driver,Medicaid,Current Smoker,"$75,000-$99,999"
3,PAT030794,Carol,Martin,Female,1959-11-01,65,AB+,TWO OR MORE RACES,Single,SOFTWARE DEVELOPER,Medicare,Current Smoker,"$100,000-$149,999"
4,PAT016673,Victoria,Jones,Other,1958-01-06,67,O+,Black or African American,Married,Electrician,NaN,Current Smoker,"$75,000-$99,999"

In [21]:
patient.tail()

,patient_id,first_name,last_name,gender,date_of_birth,age,blood_group,ethnicity,marital_status,occupation,insurance_type,smoking_status,income_bracket
43195,PAT005521,Kelly,Murray,Female,1967-02-11,57,AB-,Native American,Separated,Sales Representative,Employer-Sponsored,Current Smoker,"$50,000-$74,999"
43196,PAT035815,ELLEN,Landry,Female,1976-07-07,48,A-,Black or African American,Widowed,Accountant,Uninsured,Current Smoker,"$150,000+"
43197,PAT020464,JERRY,Kennedy,Male,2009-05-01,15,A+,Pacific Islander,Single,Student,Military/VA,Current Smoker,"Under $25,000"
43198,PAT018639,Matthew,Williams,Other,1957-05-03,67,O+,Two or More Races,Married,Student,Private Insurance,Current Smoker,"$100,000-$149,999"
43199,PAT035684,Edward,Spencer,Other,1975-07-02,49,A-,Native American,Widowed,Business Owner,Private Insurance,NEVER SMOKED,"Under $25,000"

In [22]:
patient.shape # 43200 rows and 13 columns

(43200, 13)

In [23]:
patient.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43200 entries, 0 to 43199
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patient_id      43200 non-null  object
 1   first_name      43200 non-null  object
 2   last_name       43200 non-null  object
 3   gender          41468 non-null  object
 4   date_of_birth   41879 non-null  object
 5   age             43200 non-null  int64
 6   blood_group     40150 non-null  object
 7   ethnicity       41043 non-null  object
 8   marital_status  40606 non-null  object
 9   occupation      39740 non-null  object
 10  insurance_type  41027 non-null  object
 11  smoking_status  41039 non-null  object
 12  income_bracket  38877 non-null  object
dtypes: int64(1), object(12)
memory usage: 4.3+ MB

> Date of birth - date

In [24]:
patient.describe()

                age
count  43200.000000
mean      45.789375
std       27.517260
min       -2.000000
25%       22.000000
50%       46.000000
75%       70.000000
max       94.000000

> Need to handle negative ages

In [25]:
patient.isna().sum()

patient_id           0
first_name           0
last_name            0
gender            1732
date_of_birth     1321
age                  0
blood_group       3050
ethnicity         2157
marital_status    2594
occupation        3460
insurance_type    2173
smoking_status    2161
income_bracket    4323
dtype: int64

> Null values exist

In [26]:
patient.duplicated().sum()

np.int64(3200)

In [27]:
patient['patient_id'].duplicated().sum()

np.int64(3200)

In [28]:
patient[patient['patient_id'].duplicated(keep=False)].sort_values('patient_id')

,patient_id,first_name,last_name,gender,date_of_birth,age,blood_group,ethnicity,marital_status,occupation,insurance_type,smoking_status,income_bracket
7855,PAT000012,Kimberly,Burgess,Female,1971-10-27,53,B-,Two or More Races,Married,Electrician,NaN,Former Smoker,"$75,000-$99,999"
32085,PAT000012,Kimberly,Burgess,Female,1971-10-27,53,B-,Two or More Races,Married,Electrician,NaN,Former Smoker,"$75,000-$99,999"
19093,PAT000014,Brenda,Snyder,female,2003-03-31,21,O+,Native American,Widowed,NaN,medicare,Current Smoker,"$50,000-$74,999"
17776,PAT000014,Brenda,Snyder,female,2003-03-31,21,O+,Native American,Widowed,NaN,medicare,Current Smoker,"$50,000-$74,999"
8164,PAT000022,Jennifer,Stanton,Other,2003-11-03,21,A+,White,Single,CONSTRUCTION WORKER,Military/VA,Former Smoker,"$75,000-$99,999"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23300,PAT039937,Tyler,Hudson,Other,2001-09-17,23,B+,White,Married,Retired,Medicaid,Current Smoker,"Under $25,000"
15868,PAT039955,Stephanie,WILLIAMS,Female,1990-04-07,34,B-,Asian,Divorced,Factory Worker,medicaid,Never Smoked,"$25,000-$49,999"
21282,PAT039955,Stephanie,WILLIAMS,Female,1990-04-07,34,B-,Asian,Divorced,Factory Worker,medicaid,Never Smoked,"$25,000-$49,999"
30075,PAT039983,Derek,Wilson,Other,2023-02-06,1,AB-,Asian,Single,Student,Military/VA,Never Smoked,"$100,000-$149,999"
4462,PAT039983,Derek,Wilson,Other,2023-02-06,1,AB-,Asian,Single,Student,Military/VA,Never Smoked,"$100,000-$149,999"

> Duplicates needs to be removed

In [29]:
Missing_Summary = pd.DataFrame({'Missing count':patient.isnull().sum(),'Missing %': patient.isnull().mean()*100}).round(2)
Missing_Summary

                Missing count  Missing %
patient_id                  0       0.00
first_name                  0       0.00
last_name                   0       0.00
gender                   1732       4.01
date_of_birth            1321       3.06
age                         0       0.00
blood_group              3050       7.06
ethnicity                2157       4.99
marital_status           2594       6.00
occupation               3460       8.01
insurance_type           2173       5.03
smoking_status           2161       5.00
income_bracket           4323      10.01

In [30]:
location.head()

,location_id,city,state,region,country,zip_code,population_density_per_sqkm
0,LOC0069,Little Rock,AR,South,USA,6507.0,10197.0
1,LOC0059,richmond,VA,South,USA,10829.0,7091.0
2,LOC0073,Charleston,SC,South,USA,10959.0,3123.0
3,LOC0010,Dallas,TX,south,USA,13935.0,5628.0
4,LOC0071,Anchorage,AK,West,USA,30372.0,3993.0

In [31]:
location.tail()

,location_id,city,state,region,country,zip_code,population_density_per_sqkm
87,LOC0001,NEW YORK,NY,Northeast,USA,84311.0,7320.0
88,LOC0073,Charleston,SC,South,USA,10959.0,3123.0
89,LOC0057,Salt Lake City,Ut,West,USA,16862.0,7563.0
90,LOC0004,San Francisco,CA,WEST,USA,97697.0,5241.0
91,LOC0025,Charlotte,nc,South,USA,74064.0,3435.0

In [32]:
location.shape # 92 rows and 7 columns

(92, 7)

In [33]:
location.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   location_id                  92 non-null     object
 1   city                         92 non-null     object
 2   state                        92 non-null     object
 3   region                       92 non-null     object
 4   country                      92 non-null     object
 5   zip_code                     81 non-null     float64
 6   population_density_per_sqkm  78 non-null     float64
dtypes: float64(2), object(5)
memory usage: 5.2+ KB

> Zip code - int64

In [34]:
location.describe()

           zip_code  population_density_per_sqkm
count     81.000000                    78.000000
mean   44901.172840                  6163.102564
std    30572.630173                  3392.565736
min     1352.000000                   239.000000
25%    16862.000000                  3142.750000
50%    36935.000000                  6034.500000
75%    74064.000000                  9134.750000
max    97697.000000                 11686.000000

In [35]:
location.isnull().sum()

location_id                     0
city                            0
state                           0
region                          0
country                         0
zip_code                       11
population_density_per_sqkm    14
dtype: int64

> Null values exists

In [36]:
location.duplicated().sum()

np.int64(15)

In [37]:
location[location.duplicated(keep=False)].sort_values('location_id')

,location_id,city,state,region,country,zip_code,population_density_per_sqkm
90,LOC0004,San Francisco,CA,WEST,USA,97697.0,5241.0
9,LOC0004,San Francisco,CA,WEST,USA,97697.0,5241.0
40,LOC0014,Tucson,AZ,West,USA,11896.0,8372.0
28,LOC0014,Tucson,AZ,West,USA,11896.0,8372.0
85,LOC0020,ORLANDO,FL,south,USA,29158.0,NaN
10,LOC0020,ORLANDO,FL,south,USA,29158.0,NaN
66,LOC0020,ORLANDO,FL,south,USA,29158.0,NaN
86,LOC0022,columbus,OH,Midwest,USA,66738.0,6470.0
56,LOC0022,columbus,OH,Midwest,USA,66738.0,6470.0
33,LOC0024,Cincinnati,OH,Midwest,USA,3979.0,NaN
30,LOC0024,Cincinnati,OH,Midwest,USA,3979.0,NaN
21,LOC0032,Boston,MA,Northeast,USA,29394.0,2097.0
12,LOC0032,Boston,MA,Northeast,USA,29394.0,2097.0
80,LOC0039,Eugene,OR,West,USA,55893.0,4708.0
50,LOC0039,Eugene,OR,West,USA,55893.0,4708.0
81,LOC0042,Louisville,KY,South,USA,20880.0,1317.0
83,LOC0042,Louisville,KY,South,USA,20880.0,1317.0
25,LOC0043,Baltimore,MD,South,USA,28722.0,1578.0
63,LOC0043,Baltimore,MD,South,USA,28722.0,1578.0
53,LOC0049,Savannah,GA,South,USA,47553.0,5443.0
58,LOC0049,Savannah,GA,South,USA,47553.0,5443.0
45,LOC0065,Newark,NJ,NORTHEAST,usa,76175.0,10798.0
8,LOC0065,Newark,NJ,NORTHEAST,usa,76175.0,10798.0
35,LOC0071,Anchorage,AK,West,USA,30372.0,3993.0
4,LOC0071,Anchorage,AK,West,USA,30372.0,3993.0
88,LOC0073,Charleston,SC,South,USA,10959.0,3123.0
2,LOC0073,Charleston,SC,South,USA,10959.0,3123.0
13,LOC0074,Columbia,SC,South,USA,31013.0,1071.0
48,LOC0074,Columbia,SC,South,USA,31013.0,1071.0

> Duplicates needs to be removed

In [38]:
Missing_Summary = pd.DataFrame({'Missing count':location.isnull().sum(),'Missing %': location.isnull().mean()*100}).round(2)
Missing_Summary

                             Missing count  Missing %
location_id                              0       0.00
city                                     0       0.00
state                                    0       0.00
region                                   0       0.00
country                                  0       0.00
zip_code                                11      11.96
population_density_per_sqkm             14      15.22

In [39]:
hospital.head()

,hospital_id,hospital_name,hospital_type,ownership_type,city,state,bed_capacity,accreditation_status,established_year
0,HOS0064,jackson university hospital,general hospital,Private,Jackson,MS,250.0,NaN,1928
1,HOS0035,Virginia Beach Medical Center #035,Community Hospital,Non-Profit,Virginia Beach,VA,NaN,Not Accredited,1974
2,HOS0186,Savannah Community Health Center #186,General Hospital,University-Affiliated,Savannah,GA,200.0,NABH Accredited,1935
3,HOS0147,Tulsa Health System,General Hospital,Non-Profit,Tulsa,OK,NaN,NaN,1984
4,HOS0131,Charlotte General Hospital #131,Children's Hospital,Government,CHARLOTTE,NC,300.0,Not Accredited,1997

In [40]:
hospital.tail()

,hospital_id,hospital_name,hospital_type,ownership_type,city,state,bed_capacity,accreditation_status,established_year
340,HOS0115,Orlando Medical Center #115,Children's Hospital,PRIVATE,Orlando,fl,200.0,JCI Accredited,1926
341,HOS0088,Oklahoma City University Hospital #088,Specialty Clinic,University-Affiliated,Oklahoma City,OK,NaN,NaN,1970
342,HOS0198,BALTIMORE HEALTH SYSTEM,Teaching Hospital,Non-Profit,Baltimore,MD,300.0,Not Accredited,1978
343,HOS0175,BUFFALO COMMUNITY HEALTH CENTER #175,General Hospital,University-Affiliated,buffalo,NY,75.0,NABH Accredited,1948
344,HOS0123,Kansas City Regional Hospital,Teaching Hospital,GOVERNMENT,Kansas City,MO,100.0,NABH Accredited,1942

In [41]:
hospital.shape # 345 rows and 9 columns

(345, 9)

In [42]:
hospital.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345 entries, 0 to 344
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   hospital_id           345 non-null    object
 1   hospital_name         345 non-null    object
 2   hospital_type         345 non-null    object
 3   ownership_type        310 non-null    object
 4   city                  345 non-null    object
 5   state                 345 non-null    object
 6   bed_capacity          310 non-null    float64
 7   accreditation_status  303 non-null    object
 8   established_year      345 non-null    int64
dtypes: float64(1), int64(1), object(7)
memory usage: 24.4+ KB

In [43]:
hospital.describe()

       bed_capacity  established_year
count    310.000000        345.000000
mean     351.209677       1966.524638
std      292.566599         28.025945
min       50.000000       1920.000000
25%      100.000000       1941.000000
50%      250.000000       1967.000000
75%      500.000000       1992.000000
max     1000.000000       2015.000000

In [44]:
hospital.isna().sum()

hospital_id              0
hospital_name            0
hospital_type            0
ownership_type          35
city                     0
state                    0
bed_capacity            35
accreditation_status    42
established_year         0
dtype: int64

> Null values exists

In [45]:
hospital.duplicated().sum()

np.int64(45)

In [46]:
hospital[hospital['hospital_id'].duplicated(keep=False)].sort_values('hospital_id')

,hospital_id,hospital_name,hospital_type,ownership_type,city,state,bed_capacity,accreditation_status,established_year
161,HOS0002,Tucson Regional Hospital #002,Teaching Hospital,Government,tucson,AZ,150.0,JCI Accredited,1968
50,HOS0002,Tucson Regional Hospital #002,Teaching Hospital,Government,tucson,AZ,150.0,JCI Accredited,1968
242,HOS0019,Charleston Community Health Center #019,Teaching Hospital,Private,Charleston,SC,50.0,NABH Accredited,1992
287,HOS0019,Charleston Community Health Center #019,Teaching Hospital,Private,Charleston,SC,50.0,NABH Accredited,1992
40,HOS0019,Charleston Community Health Center #019,Teaching Hospital,Private,Charleston,SC,50.0,NABH Accredited,1992
...,...,...,...,...,...,...,...,...,...
121,HOS0271,Minneapolis General Hospital,Community Hospital,Government,Minneapolis,MN,200.0,NABH Accredited,1925
65,HOS0287,Chicago Memorial Hospital,Specialty Clinic,NaN,Chicago,IL,50.0,NABH Accredited,1983
210,HOS0287,Chicago Memorial Hospital,Specialty Clinic,NaN,Chicago,IL,50.0,NABH Accredited,1983
331,HOS0295,Austin Memorial Hospital #295,COMMUNITY HOSPITAL,University-Affiliated,AUSTIN,TX,500.0,CMS Certified,1972
259,HOS0295,Austin Memorial Hospital #295,COMMUNITY HOSPITAL,University-Affiliated,AUSTIN,TX,500.0,CMS Certified,1972

> Duplicates needs to be removed

In [47]:
Missing_Summary = pd.DataFrame({'Missing count':hospital.isnull().sum(),'Missing %': hospital.isnull().mean()*100}).round(2)
Missing_Summary

                      Missing count  Missing %
hospital_id                       0       0.00
hospital_name                     0       0.00
hospital_type                     0       0.00
ownership_type                   35      10.14
city                              0       0.00
state                             0       0.00
bed_capacity                     35      10.14
accreditation_status             42      12.17
established_year                  0       0.00

In [48]:
disease.head()

,disease_id,disease_name,disease_category,icd10_code,chronic_flag,transmission_type,severity_level,avg_recovery_days
0,DIS039,Colorectal Cancer,Oncology,C18,Yes,Non-communicable,Severe,NaN
1,DIS038,lung cancer,Oncology,C34,Yes,Non-communicable,Chronic-Managed,NaN
2,DIS033,Alzheimer's Disease,Neurological,G30,Yes,Non-communicable,Severe,NaN
3,DIS045,Psoriasis,Dermatological,L40,Yes,Non-communicable,Moderate,NaN
4,DIS049,Irritable Bowel Syndrome,Digestive,K58,Yes,Non-communicable,NaN,NaN

In [49]:
disease.tail()

,disease_id,disease_name,disease_category,icd10_code,chronic_flag,transmission_type,severity_level,avg_recovery_days
48,DIS023,Cholera,Infectious,A00,No,Waterborne,Severe,20.0
49,DIS009,Pneumonia,Respiratory,J18,No,airborne,Severe,11.0
50,DIS046,Eczema,Dermatological,L20,Yes,Non-communicable,NaN,NaN
51,DIS016,Acute Kidney Injury,Renal,N17,No,Non-communicable,Moderate,20.0
52,DIS041,Leukemia,Oncology,C95,Yes,Non-communicable,Severe,NaN

In [50]:
disease.shape # 53 rows and 8 columns

(53, 8)

In [51]:
disease.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   disease_id         53 non-null     object
 1   disease_name       53 non-null     object
 2   disease_category   53 non-null     object
 3   icd10_code         53 non-null     object
 4   chronic_flag       53 non-null     object
 5   transmission_type  53 non-null     object
 6   severity_level     49 non-null     object
 7   avg_recovery_days  17 non-null     float64
dtypes: float64(1), object(7)
memory usage: 3.4+ KB

In [52]:
disease.describe()

       avg_recovery_days
count          17.000000
mean           18.235294
std             8.295552
min             4.000000
25%            12.000000
50%            20.000000
75%            23.000000
max            30.000000

In [53]:
disease.isna().sum()

disease_id            0
disease_name          0
disease_category      0
icd10_code            0
chronic_flag          0
transmission_type     0
severity_level        4
avg_recovery_days    36
dtype: int64

> Null values exist

In [54]:
disease.duplicated().sum()

np.int64(3)

In [55]:
disease[disease['disease_id'].duplicated(keep=False)].sort_values('disease_id')

,disease_id,disease_name,disease_category,icd10_code,chronic_flag,transmission_type,severity_level,avg_recovery_days
40,DIS023,Cholera,Infectious,A00,No,Waterborne,Severe,20.0
48,DIS023,Cholera,Infectious,A00,No,Waterborne,Severe,20.0
17,DIS037,Breast Cancer,Oncology,C50,Yes,Non-communicable,Moderate,NaN
22,DIS037,Breast Cancer,Oncology,C50,Yes,Non-communicable,Moderate,NaN
1,DIS038,lung cancer,Oncology,C34,Yes,Non-communicable,Chronic-Managed,NaN
44,DIS038,lung cancer,Oncology,C34,Yes,Non-communicable,Chronic-Managed,NaN

> Duplicates needs to be removed

In [56]:
Missing_Summary = pd.DataFrame({'Missing count':disease.isnull().sum(),'Missing %': disease.isnull().mean()*100}).round(2)
Missing_Summary

                   Missing count  Missing %
disease_id                     0       0.00
disease_name                   0       0.00
disease_category               0       0.00
icd10_code                     0       0.00
chronic_flag                   0       0.00
transmission_type              0       0.00
severity_level                 4       7.55
avg_recovery_days             36      67.92

In [57]:
date.head()

,date_id,full_date,day,month,month_name,quarter,year,day_of_week,is_weekend,fiscal_year
0,20221017,2022-10-17,17.0,10,October,Q4,2022,Monday,False,FY2023
1,20230130,2023-01-30,30.0,1,January,Q1,2023,Monday,False,fy2023
2,20241107,2024-11-07,7.0,11,november,q4,2024,Thursday,False,FY2025
3,20230816,2023-08-16,16.0,8,August,Q3,2023,Wednesday,False,FY2024
4,20220329,2022-03-29,29.0,3,March,Q1,2022,Tuesday,False,FY2022

In [58]:
date.tail()

,date_id,full_date,day,month,month_name,quarter,year,day_of_week,is_weekend,fiscal_year
1894,20230625,2023-06-25,25.0,6,June,Q2,2023,Sunday,True,FY2024
1895,20230619,2023-06-19,19.0,6,june,Q2,2023,Monday,False,FY2024
1896,20240102,2024-01-02,2.0,1,January,Q1,2024,Tuesday,False,FY2024
1897,20210824,2021-08-24,24.0,8,August,Q3,2021,Tuesday,False,FY2022
1898,20231128,2023-11-28,28.0,11,NOVEMBER,Q4,2023,Tuesday,False,FY2024

In [59]:
date.shape # 1899 rows and 10 columns

(1899, 10)

In [60]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1899 entries, 0 to 1898
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date_id      1899 non-null   int64
 1   full_date    1899 non-null   object
 2   day          1806 non-null   float64
 3   month        1899 non-null   int64
 4   month_name   1899 non-null   object
 5   quarter      1899 non-null   object
 6   year         1899 non-null   int64
 7   day_of_week  1899 non-null   object
 8   is_weekend   1698 non-null   object
 9   fiscal_year  1899 non-null   object
dtypes: float64(1), int64(3), object(6)
memory usage: 148.5+ KB

> full date - date

In [61]:
date.describe()

            date_id          day       month         year
count  1.899000e+03  1806.000000  1899.00000  1899.000000
mean   2.022577e+07    15.841085     6.49921  2022.510795
std    1.116018e+04     8.820632     3.43652     1.116626
min    2.021010e+07     1.000000     1.00000  2021.000000
25%    2.022011e+07     8.000000     4.00000  2022.000000
50%    2.023010e+07    16.000000     6.00000  2023.000000
75%    2.024011e+07    23.000000    10.00000  2024.000000
max    2.024123e+07    31.000000    12.00000  2024.000000

In [62]:
date.isna().sum()

date_id          0
full_date        0
day             93
month            0
month_name       0
quarter          0
year             0
day_of_week      0
is_weekend     201
fiscal_year      0
dtype: int64

> Null values exist

In [63]:
date.duplicated().sum()

np.int64(438)

In [64]:
date[date['date_id'].duplicated(keep=False)].sort_values('date_id')

,date_id,full_date,day,month,month_name,quarter,year,day_of_week,is_weekend,fiscal_year
276,20210104,2021-01-04,4.0,1,January,Q1,2021,Monday,False,FY2021
1263,20210104,2021-01-04,4.0,1,January,Q1,2021,Monday,False,FY2021
1828,20210116,2021-01-16,16.0,1,JANUARY,Q1,2021,saturday,True,FY2021
815,20210116,2021-01-16,16.0,1,JANUARY,Q1,2021,saturday,True,FY2021
945,20210118,2021-01-18,18.0,1,January,Q1,2021,Monday,False,FY2021
...,...,...,...,...,...,...,...,...,...,...
1600,20241218,2024-12-18,18.0,12,December,Q4,2024,Wednesday,False,FY2025
393,20241219,2024-12-19,19.0,12,December,Q4,2024,Thursday,False,FY2025
1683,20241219,2024-12-19,19.0,12,December,Q4,2024,Thursday,False,FY2025
518,20241228,2024-12-28,28.0,12,December,Q4,2024,Saturday,True,FY2025
1703,20241228,2024-12-28,28.0,12,December,Q4,2024,Saturday,True,FY2025

> Duplicates needs to be removed

In [65]:
Missing_Summary = pd.DataFrame({'Missing count':date.isnull().sum(),'Missing %': date.isnull().mean()*100}).round(2)
Missing_Summary

             Missing count  Missing %
date_id                  0       0.00
full_date                0       0.00
day                     93       4.90
month                    0       0.00
month_name               0       0.00
quarter                  0       0.00
year                     0       0.00
day_of_week              0       0.00
is_weekend             201      10.58
fiscal_year              0       0.00

## 2. Data Cleaning

In [66]:
fact_disease_incident.columns

Index(['incident_id', 'date_id', 'patient_id', 'disease_id', 'location_id',
       'hospital_id', 'admission_type', 'length_of_stay_days',
       'treatment_cost_usd', 'insurance_claim_amount_usd', 'outcome',
       'follow_up_required', 'readmission_flag', 'symptom_severity_score'],
      dtype='object')

In [67]:
col = ['length_of_stay_days','symptom_severity_score']

for i in col:
    fact_disease_incident[i] = pd.to_numeric(fact_disease_incident[i], errors='coerce').astype('Int64')

In [68]:
fact_disease_incident[col].dtypes

length_of_stay_days       Int64
symptom_severity_score    Int64
dtype: object

In [69]:
fact_disease_incident.head()

,incident_id,date_id,patient_id,disease_id,location_id,hospital_id,admission_type,length_of_stay_days,treatment_cost_usd,insurance_claim_amount_usd,outcome,follow_up_required,readmission_flag,symptom_severity_score
0,INC0254876,20240126,PAT004852,DIS049,LOC0058,HOS0189,Outpatient,8,2362.43,1255.48,Recovered,Yes,No,10
1,INC0191764,20230730,PAT024263,DIS003,LOC0003,HOS0152,Elective,7,4822.12,3582.07,Recovered,Yes,No,7
2,INC0153710,20241111,PAT037790,DIS047,LOC0020,HOS0045,Emergency,18,4012.48,2185.31,ONGOING TREATMENT,Yes,No,3
3,INC0198303,20230703,PAT003461,DIS021,LOC0037,HOS0279,Urgent,14,8837.01,7034.78,Recovered,Yes,No,8
4,INC0221027,20240620,PAT018040,DIS016,LOC0042,HOS0113,Elective,7,1056.38,511.05,Recovered,No,No,2

In [70]:
fact_disease_incident[fact_disease_incident.isna().any(axis=1)]

,incident_id,date_id,patient_id,disease_id,location_id,hospital_id,admission_type,length_of_stay_days,treatment_cost_usd,insurance_claim_amount_usd,outcome,follow_up_required,readmission_flag,symptom_severity_score
6,INC0231003,20240307,PAT013347,DIS030,LOC0050,HOS0104,Emergency,14,5894.19,5510.33,Recovered,No,NaN,5
7,INC0244331,20240208,PAT002824,DIS034,LOC0001,HOS0288,Urgent,<NA>,2566.51,2254.07,Recovered,Yes,No,1
8,INC0064065,20241211,PAT036061,DIS021,LOC0032,HOS0015,Outpatient,4,NaN,3215.06,Recovered,Yes,No,8
14,INC0013147,20210607,PAT030614,DIS035,LOC0049,HOS0012,Outpatient,17,NaN,2959.06,REFERRED,Yes,No,2
21,INC0068350,20210821,PAT004167,DIS043,LOC0009,HOS0031,Elective,10,1110.61,577.00,NaN,No,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365793,INC0186687,20231108,PAT039351,DIS029,LOC0062,HOS0179,Outpatient,18,5788.08,NaN,Recovered,Yes,NO,2
365795,INC0195950,20240305,PAT027168,DIS049,LOC0014,HOS0114,Elective,10,2174.63,NaN,Recovered,no,No,10
365796,INC0266859,20210824,PAT021755,DIS035,LOC0010,HOS0158,Emergency,6,2161.31,983.12,Recovered,No,NaN,<NA>
365798,INC0303332,20210922,PAT018468,DIS043,LOC0072,HOS0268,Emergency,<NA>,5196.33,2290.55,Referred,No,Yes,9
365799,INC0162699,20210214,PAT010204,DIS043,LOC0048,HOS0071,Emergency,7,4510.58,NaN,NaN,Yes,Yes,10

In [71]:
fact_disease_incident.isna().sum()

incident_id                       0
date_id                           0
patient_id                        0
disease_id                        0
location_id                       0
hospital_id                       0
admission_type                29200
length_of_stay_days           29216
treatment_cost_usd            36597
insurance_claim_amount_usd    36774
outcome                       29236
follow_up_required            29185
readmission_flag              29357
symptom_severity_score        21941
dtype: int64

In [72]:
fact_disease_incident['admission_type'] = fact_disease_incident['admission_type'].fillna('Unknown')

In [73]:
fact_disease_incident['length_of_stay_days'] = fact_disease_incident['length_of_stay_days'].fillna(fact_disease_incident['length_of_stay_days'].median())

In [74]:
fact_disease_incident['treatment_cost_usd'] = fact_disease_incident['treatment_cost_usd'].fillna(fact_disease_incident['treatment_cost_usd'].median())

In [75]:
fact_disease_incident['insurance_claim_amount_usd'] = fact_disease_incident['insurance_claim_amount_usd'].fillna(fact_disease_incident['insurance_claim_amount_usd'].median())

In [76]:
fact_disease_incident['outcome'] = fact_disease_incident['outcome'].fillna('Unknown')

In [77]:
fact_disease_incident['follow_up_required'] = fact_disease_incident['follow_up_required'].fillna('Unknown')
fact_disease_incident['readmission_flag'] = fact_disease_incident['readmission_flag'].fillna('Unknown')

In [78]:
fact_disease_incident['symptom_severity_score'].value_counts()

symptom_severity_score
5     34809
2     34603
10    34496
7     34481
4     34463
8     34440
9     34388
3     34383
6     34101
1     33695
Name: count, dtype: Int64

In [79]:
fact_disease_incident['symptom_severity_score'] = fact_disease_incident['symptom_severity_score'].fillna(0)

In [80]:
# Before removing duplicates
fact_disease_incident.shape

(365800, 14)

In [81]:
fact_disease_incident = fact_disease_incident.drop_duplicates(subset='incident_id',keep='first')

In [82]:
# After removing duplicates
fact_disease_incident.shape

(310000, 14)

In [83]:
fact_disease_incident.duplicated().sum()

np.int64(0)

In [84]:
fact_disease_incident.isna().sum()

incident_id                   0
date_id                       0
patient_id                    0
disease_id                    0
location_id                   0
hospital_id                   0
admission_type                0
length_of_stay_days           0
treatment_cost_usd            0
insurance_claim_amount_usd    0
outcome                       0
follow_up_required            0
readmission_flag              0
symptom_severity_score        0
dtype: int64

In [85]:
fact_disease_incident['incident_id'].nunique()

310000

In [86]:
fact_disease_incident[fact_disease_incident['incident_id'] != fact_disease_incident['incident_id'].str.upper()]

Empty DataFrame
Columns: [incident_id, date_id, patient_id, disease_id, location_id, hospital_id, admission_type, length_of_stay_days, treatment_cost_usd, insurance_claim_amount_usd, outcome, follow_up_required, readmission_flag, symptom_severity_score]
Index: []

In [87]:
fact_disease_incident[
    ~fact_disease_incident['incident_id'].str.match(r'^INC[A-Z0-9]*$', na=False)
]

Empty DataFrame
Columns: [incident_id, date_id, patient_id, disease_id, location_id, hospital_id, admission_type, length_of_stay_days, treatment_cost_usd, insurance_claim_amount_usd, outcome, follow_up_required, readmission_flag, symptom_severity_score]
Index: []

In [88]:
fact_disease_incident['date_id'].nunique()

1461

In [89]:
fact_disease_incident['patient_id'].nunique()

39983

In [90]:
fact_disease_incident[
    ~fact_disease_incident['patient_id'].str.match(r'^PAT[A-Z0-9]*$', na=False)
]

Empty DataFrame
Columns: [incident_id, date_id, patient_id, disease_id, location_id, hospital_id, admission_type, length_of_stay_days, treatment_cost_usd, insurance_claim_amount_usd, outcome, follow_up_required, readmission_flag, symptom_severity_score]
Index: []

In [91]:
fact_disease_incident[~fact_disease_incident['date_id'].astype('string').str.match(r'^\d{8}$', na=False)]

Empty DataFrame
Columns: [incident_id, date_id, patient_id, disease_id, location_id, hospital_id, admission_type, length_of_stay_days, treatment_cost_usd, insurance_claim_amount_usd, outcome, follow_up_required, readmission_flag, symptom_severity_score]
Index: []

In [92]:
fact_disease_incident[
    ~fact_disease_incident['disease_id'].str.match(r'^DIS[A-Z0-9]*$', na=False)
]

Empty DataFrame
Columns: [incident_id, date_id, patient_id, disease_id, location_id, hospital_id, admission_type, length_of_stay_days, treatment_cost_usd, insurance_claim_amount_usd, outcome, follow_up_required, readmission_flag, symptom_severity_score]
Index: []

In [93]:
fact_disease_incident[
    ~fact_disease_incident['location_id'].str.match(r'^LOC[A-Z0-9]*$', na=False)
]

Empty DataFrame
Columns: [incident_id, date_id, patient_id, disease_id, location_id, hospital_id, admission_type, length_of_stay_days, treatment_cost_usd, insurance_claim_amount_usd, outcome, follow_up_required, readmission_flag, symptom_severity_score]
Index: []

In [94]:
fact_disease_incident[
    ~fact_disease_incident['hospital_id'].str.match(r'^HOS[A-Z0-9]*$', na=False)
]

Empty DataFrame
Columns: [incident_id, date_id, patient_id, disease_id, location_id, hospital_id, admission_type, length_of_stay_days, treatment_cost_usd, insurance_claim_amount_usd, outcome, follow_up_required, readmission_flag, symptom_severity_score]
Index: []

In [95]:
fact_disease_incident['admission_type'] = fact_disease_incident['admission_type'].str.strip().str.title()

In [96]:
fact_disease_incident['admission_type'].unique()

array(['Outpatient', 'Elective', 'Emergency', 'Urgent', 'Newborn',
       'Unknown'], dtype=object)

In [97]:
fact_disease_incident['admission_type'].value_counts()

admission_type
Emergency     85837
Elective      71076
Urgent        57204
Outpatient    56760
Unknown       24800
Newborn       14323
Name: count, dtype: int64

In [98]:
fact_disease_incident['length_of_stay_days'].min()
fact_disease_incident['length_of_stay_days'].max()

np.int64(30)

In [99]:
fact_disease_incident[fact_disease_incident['treatment_cost_usd'] != fact_disease_incident['treatment_cost_usd'].round(2)]

Empty DataFrame
Columns: [incident_id, date_id, patient_id, disease_id, location_id, hospital_id, admission_type, length_of_stay_days, treatment_cost_usd, insurance_claim_amount_usd, outcome, follow_up_required, readmission_flag, symptom_severity_score]
Index: []

In [100]:
fact_disease_incident[fact_disease_incident['insurance_claim_amount_usd'] != fact_disease_incident['insurance_claim_amount_usd'].round(2)]

Empty DataFrame
Columns: [incident_id, date_id, patient_id, disease_id, location_id, hospital_id, admission_type, length_of_stay_days, treatment_cost_usd, insurance_claim_amount_usd, outcome, follow_up_required, readmission_flag, symptom_severity_score]
Index: []

In [101]:
fact_disease_incident['outcome'].unique()

array(['Recovered', 'ONGOING TREATMENT', 'Ongoing Treatment', 'Referred',
       'REFERRED', 'Recovered   ', 'Unknown', '  ongoing treatment',
       'recovered', 'ONGOING TREATMENT   ', 'RECOVERED', '  Recovered',
       '  Ongoing Treatment', 'Deceased', '  recovered',
       'DISCHARGED AGAINST MEDICAL ADVICE',
       'Discharged Against Medical Advice', '  Recovered  ',
       '  RECOVERED  ', '  Ongoing Treatment  ', '  Referred  ',
       '  recovered  ', '  RECOVERED',
       'Discharged Against Medical Advice   ', 'referred',
       'Ongoing Treatment   ', 'ongoing treatment', 'Referred   ',
       'ongoing treatment   ', '  Referred', 'recovered   ',
       'ongoing  treatment', 'RECOVERED   ', 'REFERRED   ',
       '  referred  ', '  Deceased', '  ONGOING TREATMENT', 'referred   ',
       'Deceased   ', '  Deceased  ', 'Ongoing  Treatment',
       '  Discharged Against Medical Advice', 'DECEASED',
       '  ONGOING TREATMENT  ', 'deceased', '  REFERRED', 'deceased   ',
       'discharged against medical advice', '  DECEASED',
       'ONGOING  TREATMENT', '  ongoing treatment  ', '  referred',
       '  REFERRED  ', 'Discharged  Against  Medical  Advice',
       '  DISCHARGED AGAINST MEDICAL ADVICE',
       '  discharged against medical advice',
       'discharged  against  medical  advice', '  deceased',
       'DISCHARGED AGAINST MEDICAL ADVICE   ', 'DECEASED   ',
       '  Discharged Against Medical Advice  ',
       '  discharged against medical advice  ', '  deceased  ',
       '  DISCHARGED AGAINST MEDICAL ADVICE  ', '  DECEASED  ',
       'DISCHARGED  AGAINST  MEDICAL  ADVICE',
       'discharged against medical advice   '], dtype=object)

In [102]:
fact_disease_incident['outcome'] = fact_disease_incident['outcome'].str.strip().str.title().str.replace(r'\s+', ' ', regex=True)

In [103]:
fact_disease_incident['outcome'].unique()

array(['Recovered', 'Ongoing Treatment', 'Referred', 'Unknown',
       'Deceased', 'Discharged Against Medical Advice'], dtype=object)

In [104]:
fact_disease_incident['outcome'].value_counts()

outcome
Recovered                            176813
Ongoing Treatment                     57020
Referred                              28762
Unknown                               24800
Deceased                              14103
Discharged Against Medical Advice      8502
Name: count, dtype: int64

In [105]:
fact_disease_incident['follow_up_required'].unique()

array(['Yes', 'No', 'Yes   ', '  YES  ', 'YES', 'Unknown', 'NO', 'yes',
       '  No  ', '  No', '  Yes  ', 'no', '  NO', '  YES', 'NO   ',
       '  Yes', 'YES   ', '  NO  ', 'No   ', '  no', 'yes   ', '  yes',
       'no   ', '  no  ', '  yes  '], dtype=object)

In [106]:
fact_disease_incident['follow_up_required'] = fact_disease_incident['follow_up_required'].str.strip().str.title()

In [107]:
fact_disease_incident['follow_up_required'].value_counts()

follow_up_required
Yes        157058
No         128142
Unknown     24800
Name: count, dtype: int64

In [108]:
fact_disease_incident['readmission_flag'].unique()

array(['No', 'Unknown', '  no', 'Yes', 'NO', '  No  ', 'No   ', 'no',
       '  No', 'no   ', 'YES', 'NO   ', '  NO', '  YES  ', 'yes',
       '  Yes  ', '  Yes', 'Yes   ', '  no  ', '  NO  ', '  yes', '  YES',
       'yes   ', 'YES   ', '  yes  '], dtype=object)

In [109]:
fact_disease_incident['readmission_flag'] = fact_disease_incident['readmission_flag'].str.strip().str.title()

In [110]:
fact_disease_incident['readmission_flag'].value_counts()

readmission_flag
No         251182
Yes         34018
Unknown     24800
Name: count, dtype: int64

In [111]:
fact_disease_incident['symptom_severity_score'].min()
fact_disease_incident['symptom_severity_score'].max()

np.int64(10)

In [112]:
fact_disease_incident['symptom_severity_score'].value_counts()

symptom_severity_score
5     29573
2     29288
8     29241
4     29227
10    29154
9     29140
7     29123
3     29095
6     28954
1     28605
0     18600
Name: count, dtype: Int64

In [113]:
patient.columns

Index(['patient_id', 'first_name', 'last_name', 'gender', 'date_of_birth',
       'age', 'blood_group', 'ethnicity', 'marital_status', 'occupation',
       'insurance_type', 'smoking_status', 'income_bracket'],
      dtype='object')

In [116]:
patient.dtypes

patient_id                object
first_name                object
last_name                 object
gender                    object
date_of_birth     datetime64[ns]
age                        int64
blood_group               object
ethnicity                 object
marital_status            object
occupation                object
insurance_type            object
smoking_status            object
income_bracket            object
dtype: object

In [115]:
patient['date_of_birth'] = pd.to_datetime(patient['date_of_birth'],errors='coerce')

In [125]:
patient[patient['age'] < 0]

Empty DataFrame
Columns: [patient_id, first_name, last_name, gender, date_of_birth, age, blood_group, ethnicity, marital_status, occupation, insurance_type, smoking_status, income_bracket]
Index: []

In [119]:
# corrected ages of patients
patient['age'] = (
    (pd.Timestamp.today() - patient['date_of_birth']).dt.days / 365.25
).round().astype('Int64')

In [124]:
patient[patient['patient_id'] == 'PAT035654']
patient[patient['patient_id'] == 'PAT032362']

,patient_id,first_name,last_name,gender,date_of_birth,age,blood_group,ethnicity,marital_status,occupation,insurance_type,smoking_status,income_bracket
42956,PAT032362,Jeremy,DAVIS,Male,2026-08-29,0,AB+,Two or More Races,Single,Student,Medicare,Never Smoked,"$100,000-$149,999"

In [126]:
patient[patient['patient_id'].duplicated(keep=False)].sort_values('patient_id')

,patient_id,first_name,last_name,gender,date_of_birth,age,blood_group,ethnicity,marital_status,occupation,insurance_type,smoking_status,income_bracket
7855,PAT000012,Kimberly,Burgess,Female,1971-10-27,55,B-,Two or More Races,Married,Electrician,NaN,Former Smoker,"$75,000-$99,999"
32085,PAT000012,Kimberly,Burgess,Female,1971-10-27,55,B-,Two or More Races,Married,Electrician,NaN,Former Smoker,"$75,000-$99,999"
19093,PAT000014,Brenda,Snyder,female,2003-03-31,23,O+,Native American,Widowed,NaN,medicare,Current Smoker,"$50,000-$74,999"
17776,PAT000014,Brenda,Snyder,female,2003-03-31,23,O+,Native American,Widowed,NaN,medicare,Current Smoker,"$50,000-$74,999"
8164,PAT000022,Jennifer,Stanton,Other,2003-11-03,23,A+,White,Single,CONSTRUCTION WORKER,Military/VA,Former Smoker,"$75,000-$99,999"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23300,PAT039937,Tyler,Hudson,Other,2001-09-17,25,B+,White,Married,Retired,Medicaid,Current Smoker,"Under $25,000"
15868,PAT039955,Stephanie,WILLIAMS,Female,1990-04-07,36,B-,Asian,Divorced,Factory Worker,medicaid,Never Smoked,"$25,000-$49,999"
21282,PAT039955,Stephanie,WILLIAMS,Female,1990-04-07,36,B-,Asian,Divorced,Factory Worker,medicaid,Never Smoked,"$25,000-$49,999"
30075,PAT039983,Derek,Wilson,Other,2023-02-06,4,AB-,Asian,Single,Student,Military/VA,Never Smoked,"$100,000-$149,999"
4462,PAT039983,Derek,Wilson,Other,2023-02-06,4,AB-,Asian,Single,Student,Military/VA,Never Smoked,"$100,000-$149,999"

In [127]:
# Before dropping duplicates
patient.shape

(43200, 13)

In [128]:
patient = patient.drop_duplicates(subset ='patient_id',keep='first')

In [129]:
# After dropping duplicates
patient.shape

(40000, 13)

In [130]:
patient[patient['patient_id'].duplicated(keep=False)].sort_values('patient_id')

Empty DataFrame
Columns: [patient_id, first_name, last_name, gender, date_of_birth, age, blood_group, ethnicity, marital_status, occupation, insurance_type, smoking_status, income_bracket]
Index: []

In [158]:
patient.isna().sum()

patient_id           0
first_name           0
last_name            0
gender               0
date_of_birth     1200
age                  0
blood_group          0
ethnicity            0
marital_status       0
occupation           0
insurance_type       0
smoking_status       0
income_bracket       0
dtype: int64

In [135]:
patient['gender'].unique()

array(['Female', 'Male', 'Other', 'male', 'MALE', '  FEMALE  ', 'Unknown',
       '  male', '  Female  ', 'Female   ', 'FEMALE', 'OTHER', 'female',
       '  Male', '  Female', '  MALE  ', 'male   ', 'MALE   ', 'other',
       '  Male  ', 'Male   ', '  female  ', '  FEMALE', 'female   ',
       '  male  ', '  Other', '  female', '  MALE', 'Other   ',
       'FEMALE   ', '  OTHER', 'other   ', '  other', '  Other  ',
       '  other  ', 'OTHER   '], dtype=object)

In [133]:
patient['gender'] = patient['gender'].fillna('Unknown')

In [137]:
patient[patient['date_of_birth'].isna()]

,patient_id,first_name,last_name,gender,date_of_birth,age,blood_group,ethnicity,marital_status,occupation,insurance_type,smoking_status,income_bracket
13,PAT030650,Joseph,Villegas,Male,NaT,<NA>,O-,Two or More Races,Single,Homemaker,Uninsured,Never Smoked,"$75,000-$99,999"
14,PAT026585,Nicholas,Skinner,Male,NaT,<NA>,O-,Pacific Islander,Widowed,Lawyer,Employer-Sponsored,Never Smoked,"$50,000-$74,999"
26,PAT024961,Allen,Thompson,Male,NaT,<NA>,O-,Two or More Races,Widowed,Chef,Private Insurance,Never Smoked,"$50,000-$74,999"
58,PAT023089,Luis,Robinson,Male,NaT,<NA>,B+,Asian,Separated,Student,Private Insurance,Never Smoked,"$75,000-$99,999"
75,PAT037883,Joseph,Riddle,Male,NaT,<NA>,B+,NaN,Separated,CONSTRUCTION WORKER,Military/VA,Former Smoker,"$100,000-$149,999"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42968,PAT030449,Andrew,Marshall,Male,NaT,<NA>,O+,Asian,Widowed,NaN,Uninsured,Never Smoked,"Under $25,000"
42983,PAT008586,Mary,Townsend,Female,NaT,<NA>,O-,Pacific Islander,Single,Student,Military/VA,Never Smoked,"$50,000-$74,999"
43095,PAT002994,Cynthia,Shea,Female,NaT,<NA>,A+,Black or African American,Divorced,ENGINEER,Medicare,Never Smoked,"Under $25,000"
43124,PAT006320,Brooke,Barajas,OTHER,NaT,<NA>,A-,White,MARRIED,Artist,Medicare,Former Smoker,"$100,000-$149,999"
43165,PAT003899,Damon,powell,Male,NaT,<NA>,AB+,Pacific Islander,Married,Factory Worker,Medicare,Never Smoked,"$25,000-$49,999"

In [138]:
patient['age'] = patient['age'].fillna(patient['age'].median())

In [141]:
patient['blood_group'].unique()

array(['B+', 'AB-', 'O+', 'AB+', 'O-', 'A+', 'A-', 'Unknown', 'B-'],
      dtype=object)

In [140]:
patient['blood_group'] = patient['blood_group'].fillna('Unknown')

In [143]:
patient.dtypes

patient_id                object
first_name                object
last_name                 object
gender                    object
date_of_birth     datetime64[ns]
age                        Int64
blood_group               object
ethnicity                 object
marital_status            object
occupation                object
insurance_type            object
smoking_status            object
income_bracket            object
dtype: object

In [144]:
patient['ethnicity'].unique()

array(['Pacific Islander', 'Hispanic or Latino', 'Native American',
       'TWO  OR  MORE  RACES', 'Black or African American', 'White',
       '  black or african american', 'Two or More Races',
       '  Two or More Races', 'Asian', nan, '  Asian',
       '  NATIVE AMERICAN', 'Native  American', 'two or more races',
       'NATIVE AMERICAN', 'Two or More Races   ',
       'BLACK OR AFRICAN AMERICAN', 'TWO OR MORE RACES',
       'Pacific Islander   ', '  Pacific Islander', 'pacific islander',
       'WHITE   ', 'asian', '  hispanic or latino  ', 'Pacific  Islander',
       'Hispanic Or Latino', 'hispanic or latino   ',
       'Native American   ', 'ASIAN', '  Hispanic or Latino',
       'HISPANIC  OR  LATINO', 'Hispanic or Latino   ', 'native american',
       '  WHITE', 'WHITE', '  HISPANIC OR LATINO',
       '  Black or African American', 'black or african american   ',
       '  PACIFIC ISLANDER  ', '  pacific islander',
       'Black  or  African  American', 'Black or African American   ',
       'Hispanic  or  Latino', '  Native American', '  TWO OR MORE RACES',
       'ASIAN   ', 'black or african american', 'HISPANIC OR LATINO',
       'Black Or African American', 'Hispanic Or Latino   ', 'Asian   ',
       '  Black or African American  ', 'PACIFIC ISLANDER',
       'BLACK OR AFRICAN AMERICAN   ', 'hispanic or latino', '  White  ',
       'white', '  Hispanic or Latino  ', '  two or more races',
       'asian   ', 'NATIVE AMERICAN   ', '  native american', '  asian',
       '  pacific islander  ', '  WHITE  ', '  NATIVE AMERICAN  ',
       '  Two or More Races  ', '  Native American  ', '  White',
       'Two  or  More  Races', 'White   ', 'Two Or More Races',
       'two or more races   ', 'Two Or More Races   ',
       '  Two Or More Races', '  TWO OR MORE RACES  ', '  Asian  ',
       'PACIFIC  ISLANDER', 'HISPANIC OR LATINO   ',
       'Black Or African American   ', 'TWO OR MORE RACES   ',
       'PACIFIC ISLANDER   ', 'Two  Or  More  Races',
       '  Pacific Islander  ', '  ASIAN', '  asian  ', '  ASIAN  ',
       'Black  Or  African  American', '  HISPANIC OR LATINO  ',
       'BLACK  OR  AFRICAN  AMERICAN', '  BLACK OR AFRICAN AMERICAN  ',
       '  Hispanic Or Latino', '  Black Or African American',
       'native  american', '  native american  ',
       '  black or african american  ', '  PACIFIC ISLANDER',
       'native american   ', 'NATIVE  AMERICAN', '  two or more races  ',
       '  Hispanic Or Latino  ', 'white   ', '  hispanic or latino',
       '  white', '  BLACK OR AFRICAN AMERICAN', '  white  ',
       'pacific islander   ', 'two  or  more  races',
       '  Black Or African American  ', 'Hispanic  Or  Latino',
       'pacific  islander', 'black  or  african  american',
       '  Two Or More Races  ', 'hispanic  or  latino'], dtype=object)

In [145]:
patient['ethnicity'] = patient['ethnicity'].fillna('Unknown')

In [148]:
patient['marital_status'].unique()

array(['Divorced', 'Widowed', 'Single', 'Married', 'Separated',
       '  Divorced', 'Unknown', '  widowed', '  Separated', 'MARRIED',
       'divorced', 'DIVORCED', '  SINGLE', '  separated', 'Divorced   ',
       '  Separated  ', 'married', '  Widowed', 'WIDOWED', '  Single  ',
       '  WIDOWED', 'SEPARATED', 'married   ', 'widowed', '  Single',
       '  DIVORCED', '  single', 'SINGLE', 'Widowed   ', 'single',
       'MARRIED   ', 'Single   ', 'separated', 'Married   ',
       'Separated   ', '  separated  ', 'single   ', '  Divorced  ',
       '  MARRIED  ', '  Married  ', '  Married', '  married  ',
       '  SINGLE  ', 'DIVORCED   ', 'WIDOWED   ', 'divorced   ',
       '  divorced', '  single  ', 'widowed   ', '  Widowed  ',
       'SINGLE   ', '  widowed  ', '  SEPARATED', '  divorced  ',
       'separated   ', '  married', '  SEPARATED  ', '  DIVORCED  ',
       '  MARRIED', 'SEPARATED   ', '  WIDOWED  '], dtype=object)

In [147]:
patient['marital_status'] = patient['marital_status'].fillna('Unknown')

In [150]:
patient['occupation'].unique()

array(['Software Developer', 'Artist', 'Driver', 'SOFTWARE DEVELOPER',
       'Electrician', 'Engineer', nan, 'Teacher', 'Student', 'Farmer',
       'Lawyer', 'Lawyer   ', '  Accountant  ', 'Homemaker', 'Unemployed',
       'Accountant', 'Business  Owner', 'Retired', 'Sales Representative',
       '  Student  ', 'Chef', 'STUDENT   ', 'Business Owner', '  Retired',
       'BUSINESS OWNER', '  construction worker  ', 'Teacher   ',
       'HOMEMAKER   ', 'TEACHER', '  nurse  ', 'Factory Worker',
       'CONSTRUCTION WORKER', 'Construction Worker', '  driver  ',
       'Chef   ', 'Police Officer', 'Nurse', 'POLICE OFFICER', 'STUDENT',
       '  Teacher  ', 'farmer', 'nurse', 'accountant', 'Retired   ',
       '  Factory Worker  ', '  Farmer  ', '  Police Officer', '  farmer',
       '  Unemployed', 'student', 'Business Owner   ', '  STUDENT  ',
       '  STUDENT', '  Sales Representative', 'RETIRED', 'retired',
       'Software  Developer', 'police officer', 'engineer', '  Lawyer',
       'TEACHER   ', 'unemployed', '  Student', 'Factory Worker   ',
       'chef', 'LAWYER', 'electrician   ', 'Student   ', 'Engineer   ',
       'UNEMPLOYED', '  POLICE OFFICER  ', 'teacher',
       'Software Developer   ', 'business owner', 'ACCOUNTANT', 'NURSE',
       '  BUSINESS OWNER  ', 'sales representative', 'Farmer   ',
       'lawyer', '  Software Developer  ', '  ACCOUNTANT',
       '  electrician', '  ELECTRICIAN  ', 'artist', '  homemaker',
       'business owner   ', '  Chef', '  POLICE OFFICER', 'FARMER',
       '  Lawyer  ', 'HOMEMAKER', 'software developer', 'teacher   ',
       '  Homemaker', 'Sales Representative   ', 'Nurse   ',
       '  Construction Worker', '  driver', 'homemaker', '  student  ',
       '  teacher  ', '  Business Owner', '  SALES REPRESENTATIVE',
       '  accountant  ', '  Police Officer  ', '  NURSE  ', 'electrician',
       '  ARTIST', '  Driver', '  student', '  FARMER', '  Accountant',
       '  Construction Worker  ', 'UNEMPLOYED   ', '  Unemployed  ',
       'Unemployed   ', 'sales  representative', 'student   ', '  Nurse',
       '  Artist', '  Factory Worker', '  CONSTRUCTION WORKER',
       'Homemaker   ', '  factory worker', 'Electrician   ', '  DRIVER',
       'FACTORY WORKER', '  chef', 'Police  Officer', 'Accountant   ',
       'ELECTRICIAN', 'LAWYER   ', 'ENGINEER', '  Teacher',
       'SALES REPRESENTATIVE', 'Sales  Representative',
       '  Business Owner  ', 'Artist   ', '  FACTORY WORKER',
       '  LAWYER  ', '  UNEMPLOYED', 'DRIVER', '  BUSINESS OWNER',
       'factory worker', '  Software Developer', '  lawyer',
       'accountant   ', '  unemployed', 'retired   ',
       'construction worker', 'FACTORY WORKER   ',
       '  Sales Representative  ', 'driver', 'ACCOUNTANT   ', '  chef  ',
       '  HOMEMAKER', 'CHEF', '  CONSTRUCTION WORKER  ',
       '  police officer', '  Electrician', 'POLICE OFFICER   ', 'ARTIST',
       '  Farmer', '  Engineer', '  engineer', '  artist  ',
       'Construction Worker   ', '  Electrician  ', 'Factory  Worker',
       '  FACTORY WORKER  ', '  RETIRED  ', 'ELECTRICIAN   ',
       '  Artist  ', '  FARMER  ', 'Driver   ', '  construction worker',
       '  Chef  ', 'Police Officer   ', '  LAWYER', '  ELECTRICIAN',
       '  Nurse  ', '  sales representative', 'unemployed   ',
       '  Homemaker  ', 'lawyer   ', '  SOFTWARE DEVELOPER',
       '  Engineer  ', 'ENGINEER   ', 'engineer   ', 'NURSE   ',
       'homemaker   ', '  Driver  ', '  ARTIST  ',
       'SALES  REPRESENTATIVE', '  retired', 'FARMER   ',
       '  software developer', 'police officer   ', '  DRIVER  ',
       '  sales representative  ', '  SOFTWARE DEVELOPER  ',
       '  SALES REPRESENTATIVE  ', 'CONSTRUCTION WORKER   ',
       'construction  worker', 'CONSTRUCTION  WORKER', '  UNEMPLOYED  ',
       'farmer   ', '  artist', '  ENGINEER', 'driver   ',
       'SOFTWARE DEVELOPER   ', 'software developer   ', 'ARTIST   ',
       'sales representative   ', '  RETIRED', '  farmer  ', '  teacher',
       '  lawyer  ', 'RETIRED   ', 'Construction  Worker', 'chef   ',
       'construction worker   ', '  engineer  ', '  ACCOUNTANT  ',
       '  nurse', '  accountant', 'factory  worker', '  NURSE',
       'SOFTWARE  DEVELOPER', '  ENGINEER  ', 'software  developer',
       '  CHEF', '  Retired  ', 'DRIVER   ', '  business owner  ',
       '  TEACHER  ', '  business owner', '  software developer  ',
       '  TEACHER', 'police  officer', 'factory worker   ',
       '  unemployed  ', 'nurse   ', '  retired  ',
       'SALES REPRESENTATIVE   ', '  factory worker  ',
       'BUSINESS OWNER   ', '  electrician  ', 'artist   ', '  CHEF  ',
       'CHEF   ', '  homemaker  ', '  police officer  ',
       'FACTORY  WORKER', '  HOMEMAKER  ', 'BUSINESS  OWNER'],
      dtype=object)

In [151]:
patient['occupation'] = patient['occupation'].fillna('Unknown')

In [152]:
patient['insurance_type'].unique()

array(['Employer-Sponsored', 'Medicaid', 'Medicare', nan,
       'Private Insurance', 'Uninsured', 'Military/VA', 'Military/Va',
       '  Employer-Sponsored', 'Private  Insurance', 'EMPLOYER-SPONSORED',
       'military/va', '  Medicaid', 'MEDICARE', 'UNINSURED',
       'MILITARY/VA', '  Uninsured  ', 'UNINSURED   ', 'military/va   ',
       'medicaid', '  Medicare', 'PRIVATE INSURANCE', 'Uninsured   ',
       '  Uninsured', 'MEDICAID', 'medicare', '  military/va',
       'employer-sponsored   ', '  Military/VA  ', 'employer-sponsored',
       'Military/Va   ', '  Medicaid  ', '  MEDICAID',
       '  Private Insurance', 'uninsured', '  Private Insurance  ',
       'private insurance', '  MILITARY/VA', 'MEDICARE   ',
       '  MEDICAID  ', '  medicare  ', 'PRIVATE  INSURANCE',
       'Medicaid   ', '  Military/VA', '  medicaid', '  uninsured',
       'Military/VA   ', 'Medicare   ', 'PRIVATE INSURANCE   ',
       '  EMPLOYER-SPONSORED', 'Private Insurance   ',
       'Employer-Sponsored   ', 'MEDICAID   ', '  UNINSURED',
       '  MEDICARE  ', 'medicaid   ', 'private insurance   ',
       'medicare   ', '  MEDICARE', 'MILITARY/VA   ', '  Medicare  ',
       'uninsured   ', '  Employer-Sponsored  ', '  PRIVATE INSURANCE  ',
       '  private insurance', '  MILITARY/VA  ', 'EMPLOYER-SPONSORED   ',
       '  military/va  ', '  PRIVATE INSURANCE', '  UNINSURED  ',
       '  medicare', '  medicaid  ', 'private  insurance',
       '  employer-sponsored', '  EMPLOYER-SPONSORED  ',
       '  Military/Va  ', '  private insurance  ',
       '  employer-sponsored  ', '  Military/Va', '  uninsured  '],
      dtype=object)

In [153]:
patient['insurance_type'] = patient['insurance_type'].fillna('Unknown')

In [155]:
patient['smoking_status'] = patient['smoking_status'].fillna('Unknown')

In [156]:
patient['income_bracket'].unique()

array(['$25,000-$49,999', 'Under $25,000', '$75,000-$99,999',
       '$100,000-$149,999', '$150,000+', nan, '$50,000-$74,999'],
      dtype=object)

In [157]:
patient['income_bracket'] = patient['income_bracket'].fillna('Unknown')

In [159]:
patient[
    ~patient['patient_id'].str.match(r'^PAT[A-Z0-9]*$', na=False)
]

Empty DataFrame
Columns: [patient_id, first_name, last_name, gender, date_of_birth, age, blood_group, ethnicity, marital_status, occupation, insurance_type, smoking_status, income_bracket]
Index: []

In [165]:
patient[patient['first_name'] != patient['first_name'].str.strip().str.title()]

Empty DataFrame
Columns: [patient_id, first_name, last_name, gender, date_of_birth, age, blood_group, ethnicity, marital_status, occupation, insurance_type, smoking_status, income_bracket]
Index: []

In [161]:
patient['first_name'] = patient['first_name'].str.strip().str.title()

In [166]:
patient[patient['last_name'] != patient['last_name'].str.strip().str.title()]

Empty DataFrame
Columns: [patient_id, first_name, last_name, gender, date_of_birth, age, blood_group, ethnicity, marital_status, occupation, insurance_type, smoking_status, income_bracket]
Index: []

In [163]:
patient['last_name'] = patient['last_name'].str.strip().str.title()

In [164]:
patient.head(10)

,patient_id,first_name,last_name,gender,date_of_birth,age,blood_group,ethnicity,marital_status,occupation,insurance_type,smoking_status,income_bracket
0,PAT016319,Alicia,Gomez,Female,1978-03-28,48,B+,Pacific Islander,Divorced,Software Developer,Employer-Sponsored,Never Smoked,"$25,000-$49,999"
1,PAT011155,Stacy,Nguyen,Female,2000-12-30,26,AB-,Hispanic or Latino,Widowed,Artist,Medicaid,Current Smoker,"Under $25,000"
2,PAT026587,Michael,Mckinney,Male,1944-11-15,82,O+,Native American,Divorced,Driver,Medicaid,Current Smoker,"$75,000-$99,999"
3,PAT030794,Carol,Martin,Female,1959-11-01,67,AB+,TWO OR MORE RACES,Single,SOFTWARE DEVELOPER,Medicare,Current Smoker,"$100,000-$149,999"
4,PAT016673,Victoria,Jones,Other,1958-01-06,69,O+,Black or African American,Married,Electrician,Unknown,Current Smoker,"$75,000-$99,999"
5,PAT004813,Carolyn,Moore,Female,2001-06-27,25,AB-,Hispanic or Latino,Separated,Engineer,Private Insurance,Former Smoker,"$150,000+"
6,PAT025919,Jorge,Scott,male,1978-02-04,49,B+,White,Widowed,Unknown,Medicaid,Never Smoked,"$100,000-$149,999"
7,PAT005022,Breanna,Smith,Female,2007-05-13,19,O+,Black or African American,Single,Teacher,Private Insurance,CURRENT SMOKER,"$25,000-$49,999"
8,PAT005688,Richard,Duncan,Male,1992-06-07,34,O-,Black or African American,Separated,Student,Medicaid,Former Smoker,"$100,000-$149,999"
9,PAT010522,Jane,Henry,Female,1986-02-11,41,AB-,Hispanic or Latino,Separated,Farmer,Medicaid,former smoker,Unknown

In [169]:
patient['gender'].unique()

array(['Female', 'Male', 'Other', 'Unknown'], dtype=object)

In [168]:
patient['gender'] = patient['gender'].str.strip().str.title()

In [170]:
patient['gender'].value_counts()

gender
Female     18548
Male       18346
Unknown     1600
Other       1506
Name: count, dtype: int64

In [173]:
patient[
    patient['date_of_birth'].notna() &
    ~patient['date_of_birth']
        .astype('string')
        .str.match(r'^\d{4}-\d{2}-\d{2}$', na=False)
]

Empty DataFrame
Columns: [patient_id, first_name, last_name, gender, date_of_birth, age, blood_group, ethnicity, marital_status, occupation, insurance_type, smoking_status, income_bracket]
Index: []

In [176]:
patient['age'].min()
patient['age'].max()

np.int64(96)

In [177]:
patient['blood_group'].unique()

array(['B+', 'AB-', 'O+', 'AB+', 'O-', 'A+', 'A-', 'Unknown', 'B-'],
      dtype=object)

In [178]:
patient['blood_group'].value_counts()

blood_group
B+         4798
A-         4691
A+         4677
O+         4676
B-         4636
O-         4624
AB+        4622
AB-        4476
Unknown    2800
Name: count, dtype: int64

In [183]:
patient['ethnicity'].unique()

array(['Pacific Islander', 'Hispanic Or Latino', 'Native American',
       'Two Or More Races', 'Black Or African American', 'White', 'Asian',
       'Unknown'], dtype=object)

In [182]:
patient['ethnicity'] = patient['ethnicity'].str.strip().str.title().str.replace(r'\s+', ' ', regex=True)

In [184]:
patient['ethnicity'].value_counts()

ethnicity
Hispanic Or Latino           5519
Black Or African American    5468
Asian                        5468
Two Or More Races            5441
Native American              5384
White                        5373
Pacific Islander             5347
Unknown                      2000
Name: count, dtype: int64

In [187]:
patient['marital_status'].unique()

array(['Divorced', 'Widowed', 'Single', 'Married', 'Separated', 'Unknown'],
      dtype=object)

In [186]:
patient['marital_status'] = patient['marital_status'].str.strip().str.title()

In [188]:
patient['marital_status'].value_counts()

marital_status
Single       13616
Divorced      6013
Widowed       6002
Married       5992
Separated     5977
Unknown       2400
Name: count, dtype: int64

In [191]:
patient['occupation'] = patient['occupation'].str.strip().str.title().str.replace(r'\s+', ' ', regex=True)

In [192]:
patient['occupation'].unique()

array(['Software Developer', 'Artist', 'Driver', 'Electrician',
       'Engineer', 'Unknown', 'Teacher', 'Student', 'Farmer', 'Lawyer',
       'Accountant', 'Homemaker', 'Unemployed', 'Business Owner',
       'Retired', 'Sales Representative', 'Chef', 'Construction Worker',
       'Nurse', 'Factory Worker', 'Police Officer'], dtype=object)

In [193]:
patient['occupation'].value_counts()

occupation
Student                 8240
Unknown                 3200
Teacher                 1562
Artist                  1548
Accountant              1543
Electrician             1541
Retired                 1538
Unemployed              1530
Police Officer          1523
Homemaker               1517
Nurse                   1512
Business Owner          1498
Driver                  1497
Sales Representative    1490
Chef                    1489
Lawyer                  1485
Farmer                  1472
Factory Worker          1465
Software Developer      1462
Construction Worker     1448
Engineer                1440
Name: count, dtype: int64

In [195]:
patient['insurance_type'].unique()
patient['smoking_status'].unique()

array(['Never Smoked', 'Current Smoker   ', 'Current Smoker',
       'Former Smoker', 'CURRENT SMOKER', 'former smoker', 'Unknown',
       '  Current Smoker', '  Never Smoked  ', 'current smoker   ',
       'Never Smoked   ', 'FORMER SMOKER', 'never smoked', 'NEVER SMOKED',
       'Former Smoker   ', '  Former Smoker', '  FORMER SMOKER',
       'Never  Smoked', '  Former Smoker  ', '  NEVER SMOKED',
       'never smoked   ', 'current smoker', '  never smoked  ',
       'FORMER SMOKER   ', 'former smoker   ', '  Current Smoker  ',
       '  Never Smoked', 'Current  Smoker', '  CURRENT SMOKER  ',
       'FORMER  SMOKER', '  never smoked', '  current smoker',
       'Former  Smoker', 'NEVER SMOKED   ', 'CURRENT  SMOKER',
       '  current smoker  ', 'NEVER  SMOKED', 'CURRENT SMOKER   ',
       '  FORMER SMOKER  ', '  former smoker', '  CURRENT SMOKER',
       'current  smoker', 'never  smoked', '  former smoker  ',
       '  NEVER SMOKED  ', 'former  smoker'], dtype=object)

In [197]:
textcol = ['insurance_type','smoking_status']

for col in textcol:
    patient[col] = patient[col].str.strip().str.title().str.replace(r'\s+', ' ', regex=True)

In [200]:
patient['insurance_type'].unique()

array(['Employer-Sponsored', 'Medicaid', 'Medicare', 'Unknown',
       'Private Insurance', 'Uninsured', 'Military/VA'], dtype=object)

In [199]:
patient['insurance_type'] = patient['insurance_type'].str.replace('Military/Va','Military/VA')

In [201]:
patient['smoking_status'].unique()

array(['Never Smoked', 'Current Smoker', 'Former Smoker', 'Unknown'],
      dtype=object)

In [202]:
patient['income_bracket'].unique()

array(['$25,000-$49,999', 'Under $25,000', '$75,000-$99,999',
       '$100,000-$149,999', '$150,000+', 'Unknown', '$50,000-$74,999'],
      dtype=object)

In [203]:
patient['smoking_status'].value_counts()

smoking_status
Never Smoked      17056
Current Smoker    10554
Former Smoker     10390
Unknown            2000
Name: count, dtype: int64

In [204]:
patient.isna().sum()

patient_id           0
first_name           0
last_name            0
gender               0
date_of_birth     1200
age                  0
blood_group          0
ethnicity            0
marital_status       0
occupation           0
insurance_type       0
smoking_status       0
income_bracket       0
dtype: int64

In [205]:
patient.duplicated().sum()

np.int64(0)

In [214]:
location.dtypes

location_id                     object
city                            object
state                           object
region                          object
country                         object
zip_code                         Int64
population_density_per_sqkm    float64
dtype: object

In [207]:
location['zip_code'] = pd.to_numeric(location['zip_code'],errors='coerce').astype('Int64')

In [213]:
location['population_density_per_sqkm'] = pd.to_numeric(location['population_density_per_sqkm'],errors='coerce').astype('float')

In [224]:
location.isnull().sum()

location_id                     0
city                            0
state                           0
region                          0
country                         0
zip_code                       11
population_density_per_sqkm     0
dtype: int64

In [211]:
location.head(15)

,location_id,city,state,region,country,zip_code,population_density_per_sqkm
0,LOC0069,Little Rock,AR,South,USA,6507,10197
1,LOC0059,richmond,VA,South,USA,10829,7091
2,LOC0073,Charleston,SC,South,USA,10959,3123
3,LOC0010,Dallas,TX,south,USA,13935,5628
4,LOC0071,Anchorage,AK,West,USA,30372,3993
5,LOC0046,ALBUQUERQUE,NM,West,USA,12657,3940
6,LOC0056,baton rouge,LA,South,USA,70785,11066
7,LOC0053,minneapolis,MN,midwest,USA,6196,10303
8,LOC0065,Newark,NJ,NORTHEAST,usa,76175,10798
9,LOC0004,San Francisco,CA,WEST,USA,97697,5241
10,LOC0020,ORLANDO,FL,south,USA,29158,<NA>
11,LOC0026,Raleigh,NC,South,USA,<NA>,6446
12,LOC0032,Boston,MA,Northeast,USA,29394,2097
13,LOC0074,Columbia,SC,South,USA,31013,1071
14,LOC0068,Montgomery,Al,South,USA,<NA>,3202

In [215]:
location['population_density_per_sqkm'] = location['population_density_per_sqkm'].fillna(location['population_density_per_sqkm'].median())

In [219]:
location['zip_code'].min() # 1352
location['zip_code'].max() #97697

np.int64(97697)

In [220]:
location.duplicated().sum()

np.int64(15)

In [221]:
# Before dropping duplicates
location.shape

(92, 7)

In [222]:
location = location.drop_duplicates(subset='location_id',keep='first')

In [223]:
# After dropping duplicates
location.shape

(77, 7)

In [225]:
location[
    ~location['location_id'].str.match(r'^LOC[A-Z0-9]*$', na=False)
]

Empty DataFrame
Columns: [location_id, city, state, region, country, zip_code, population_density_per_sqkm]
Index: []

In [231]:
crcol = ['city', 'region']
sccol = ['state', 'country']

location = location.copy()
for col in crcol:
    location[col] = (
        location[col]
        .str.strip()
        .str.title()
    )

In [232]:
for col in sccol:
    location[col] = (
        location[col]
        .str.strip()
        .str.upper()
    )

In [236]:
location['city'].unique()
location['region'].unique()
location['state'].unique()
location['country'].unique()

array(['USA'], dtype=object)

In [237]:
hospital

,hospital_id,hospital_name,hospital_type,ownership_type,city,state,bed_capacity,accreditation_status,established_year
0,HOS0064,jackson university hospital,general hospital,Private,Jackson,MS,250.0,NaN,1928
1,HOS0035,Virginia Beach Medical Center #035,Community Hospital,Non-Profit,Virginia Beach,VA,NaN,Not Accredited,1974
2,HOS0186,Savannah Community Health Center #186,General Hospital,University-Affiliated,Savannah,GA,200.0,NABH Accredited,1935
3,HOS0147,Tulsa Health System,General Hospital,Non-Profit,Tulsa,OK,NaN,NaN,1984
4,HOS0131,Charlotte General Hospital #131,Children's Hospital,Government,CHARLOTTE,NC,300.0,Not Accredited,1997
...,...,...,...,...,...,...,...,...,...
340,HOS0115,Orlando Medical Center #115,Children's Hospital,PRIVATE,Orlando,fl,200.0,JCI Accredited,1926
341,HOS0088,Oklahoma City University Hospital #088,Specialty Clinic,University-Affiliated,Oklahoma City,OK,NaN,NaN,1970
342,HOS0198,BALTIMORE HEALTH SYSTEM,Teaching Hospital,Non-Profit,Baltimore,MD,300.0,Not Accredited,1978
343,HOS0175,BUFFALO COMMUNITY HEALTH CENTER #175,General Hospital,University-Affiliated,buffalo,NY,75.0,NABH Accredited,1948
344,HOS0123,Kansas City Regional Hospital,Teaching Hospital,GOVERNMENT,Kansas City,MO,100.0,NABH Accredited,1942

In [244]:
hospital.isna().sum()

hospital_id              0
hospital_name            0
hospital_type            0
ownership_type           0
city                     0
state                    0
bed_capacity            35
accreditation_status     0
established_year         0
dtype: int64

In [241]:
hospital['ownership_type'].unique()

array(['Private', 'Non-Profit', 'University-Affiliated', 'Government',
       '  Government', 'Unknown', 'GOVERNMENT', 'PRIVATE', 'private',
       'non-profit', 'university-affiliated', 'Private   ',
       '  GOVERNMENT', '  Non-Profit', 'Government   ', '  Government  ',
       'NON-PROFIT', 'non-profit   ', 'Non-Profit   ', '  government',
       'UNIVERSITY-AFFILIATED   ', '  non-profit',
       'University-Affiliated   ', '  University-Affiliated',
       'UNIVERSITY-AFFILIATED', '  Non-Profit  ', 'government',
       'NON-PROFIT   ', '  Private', '  Private  ',
       '  university-affiliated', 'PRIVATE   '], dtype=object)

In [240]:
hospital['ownership_type'] = hospital['ownership_type'].fillna('Unknown')

In [243]:
hospital['accreditation_status'] = hospital['accreditation_status'].fillna('Unknown')

In [245]:
hospital.duplicated().sum()

np.int64(45)

In [246]:
# Before removing duplicates
hospital.shape

(345, 9)

In [247]:
hospital = hospital.drop_duplicates(subset='hospital_id',keep='first')

In [248]:
# After removing duplicates
hospital.shape

(300, 9)

In [249]:
hospital.dtypes

hospital_id              object
hospital_name            object
hospital_type            object
ownership_type           object
city                     object
state                    object
bed_capacity            float64
accreditation_status     object
established_year          int64
dtype: object

In [253]:
clean_col = ['hospital_name','hospital_type','ownership_type','city']

for col in clean_col:
    hospital[col] = hospital[col].str.strip().str.title().str.replace(r'\s+', ' ', regex=True)

In [262]:
hospital['hospital_name'].unique()
hospital['hospital_type'].unique()
hospital['ownership_type'].unique()
hospital['city'].unique()

array(['Jackson', 'Virginia Beach', 'Savannah', 'Tulsa', 'Charlotte',
       'Boise', 'Charleston', 'Grand Rapids', 'Provo', 'Newark',
       'Raleigh', 'Baltimore', 'Springfield', 'New York', 'Madison',
       'Milwaukee', 'Columbus', 'Omaha', 'Kansas City', 'Richmond',
       'San Diego', 'Hartford', 'Oklahoma City', 'San Francisco',
       'Chicago', 'Montgomery', 'San Jose', 'Des Moines', 'Orlando',
       'Austin', 'Anchorage', 'Providence', 'Honolulu', 'Saint Paul',
       'Boston', 'Cincinnati', 'Tucson', 'Denver', 'Indianapolis',
       'Little Rock', 'Louisville', 'Houston', 'Birmingham',
       'Los Angeles', 'Minneapolis', 'Jersey City', 'Pittsburgh',
       'Wichita', 'Phoenix', 'Salt Lake City', 'Buffalo', 'Atlanta',
       'Sacramento', 'Cleveland', 'Dallas', 'Seattle', 'St. Louis',
       'Columbia', 'Detroit', 'San Antonio', 'Albuquerque', 'Spokane',
       'Tampa', 'Eugene', 'Portland', 'Philadelphia', 'Memphis',
       'Boulder', 'Worcester', 'Baton Rouge', 'Nashville', 'Miami',
       'New Orleans', 'Jacksonville', 'Fresno'], dtype=object)

In [255]:
hospital['hospital_type'] = hospital['hospital_type'].str.replace("Children'S Hospital", "Children's Hospital")

In [258]:
hospital['hospital_name'] = (
    hospital['hospital_name']
    .str.replace(r'\s*#.*$', '', regex=True)
    .str.strip()
)

In [259]:
hospital['hospital_name'].unique()

array(['Jackson University Hospital', 'Virginia Beach Medical Center',
       'Savannah Community Health Center', 'Tulsa Health System',
       'Charlotte General Hospital', 'Boise Regional Hospital',
       'Charleston Memorial Hospital', 'Savannah Memorial Hospital',
       'Grand Rapids Community Health Center', 'Provo Memorial Hospital',
       'Newark Clinic', 'Raleigh University Hospital',
       'Baltimore Memorial Hospital', 'Springfield Clinic',
       'New York Medical Center', 'Madison Memorial Hospital',
       'Milwaukee Community Health Center', 'Columbus Regional Hospital',
       'Omaha University Hospital', 'Kansas City University Hospital',
       'Newark Regional Hospital', 'Virginia Beach General Hospital',
       'Richmond Community Health Center', 'Charlotte Health System',
       'Charleston University Hospital', 'San Diego University Hospital',
       'Hartford Community Health Center', 'Oklahoma City Medical Center',
       'San Francisco General Hospital', 'Chicago Regional Hospital',
       'Montgomery Clinic', 'San Jose General Hospital',
       'Des Moines Community Health Center', 'Orlando Medical Center',
       'San Jose Medical Center', 'Provo Medical Center',
       'Austin University Hospital', 'Orlando Health System',
       'Charleston Community Health Center', 'Newark Health System',
       'Anchorage Regional Hospital', 'Virginia Beach Regional Hospital',
       'Providence Community Health Center', 'Honolulu Health System',
       'Grand Rapids Memorial Hospital', 'Saint Paul University Hospital',
       'Boston University Hospital', 'Cincinnati Medical Center',
       'Tucson Regional Hospital', 'Jackson Clinic',
       'Omaha Memorial Hospital', 'Baltimore Regional Hospital',
       'Denver Medical Center', 'Virginia Beach Memorial Hospital',
       'Cincinnati Clinic', 'Austin Community Health Center',
       'Oklahoma City Memorial Hospital',
       'Indianapolis Memorial Hospital', 'Savannah General Hospital',
       'Omaha General Hospital', 'Austin Memorial Hospital',
       'Little Rock Clinic', 'Chicago Memorial Hospital',
       'Louisville Community Health Center', 'Houston Clinic',
       'Birmingham Regional Hospital', 'Los Angeles Clinic',
       'Minneapolis Medical Center', 'Providence Regional Hospital',
       'Jersey City Medical Center', 'Milwaukee Health System',
       'Pittsburgh Regional Hospital', 'Wichita Health System',
       'Tulsa Medical Center', 'Phoenix Health System',
       'Jackson Health System', 'Anchorage Health System',
       'Salt Lake City Clinic', 'Buffalo General Hospital',
       'Saint Paul Clinic', 'Atlanta Medical Center',
       'Madison Health System', 'Sacramento University Hospital',
       'Columbus Community Health Center',
       'Salt Lake City University Hospital',
       'Montgomery Regional Hospital', 'Pittsburgh General Hospital',
       'Indianapolis University Hospital', 'Cleveland General Hospital',
       'Dallas Medical Center', 'Columbus Clinic',
       'Charlotte Community Health Center', 'Saint Paul Medical Center',
       'Seattle Health System', 'Oklahoma City University Hospital',
       'Buffalo Regional Hospital', 'St. Louis Medical Center',
       'Columbia General Hospital', 'Detroit Regional Hospital',
       'San Antonio Clinic', 'Orlando University Hospital',
       'Chicago Clinic', 'Albuquerque Health System',
       'Spokane Medical Center', 'Denver University Hospital',
       'Minneapolis General Hospital', 'Little Rock Regional Hospital',
       'Spokane Memorial Hospital', 'Tucson University Hospital',
       'Austin General Hospital', 'Hartford Health System',
       'Louisville Clinic', 'Columbus University Hospital',
       'Richmond General Hospital', 'Tampa Memorial Hospital',
       'Springfield Regional Hospital', 'Chicago University Hospital',
       'Tampa General Hospital', 'Des Moines Medical Center',
       'Buffalo Community Health Center', 'Atlanta General Hospital',
       'Eugene Clinic', 'Portland Memorial Hospital',
       'Milwaukee General Hospital', 'Birmingham University Hospital',
       'Milwaukee Regional Hospital', 'Richmond Regional Hospital',
       'San Diego Community Health Center', 'Tulsa Clinic',
       'Philadelphia Clinic', 'Memphis Medical Center',
       'Cincinnati General Hospital', 'Boulder Community Health Center',
       'Richmond Clinic', 'Worcester Memorial Hospital', 'Dallas Clinic',
       'Anchorage University Hospital',
       'Cincinnati Community Health Center', 'Louisville Health System',
       'Honolulu Memorial Hospital', 'Wichita Regional Hospital',
       'Portland University Hospital', 'Spokane Community Health Center',
       'Baton Rouge Regional Hospital', 'New York General Hospital',
       'Raleigh General Hospital', 'Nashville General Hospital',
       'Houston General Hospital', 'Saint Paul Community Health Center',
       'Kansas City Community Health Center',
       'Milwaukee University Hospital', 'Cincinnati University Hospital',
       'New York Memorial Hospital', 'Nashville Memorial Hospital',
       'Columbia Medical Center', 'Phoenix Memorial Hospital',
       'Albuquerque Regional Hospital', 'Kansas City Health System',
       'Providence General Hospital', 'Honolulu Medical Center',
       'Cleveland Clinic', 'Miami Memorial Hospital',
       'Portland Medical Center', 'Montgomery Memorial Hospital',
       'Virginia Beach Health System', 'Buffalo Memorial Hospital',
       'Boston Medical Center', 'New York Regional Hospital',
       'Virginia Beach Clinic', 'Omaha Medical Center',
       'Provo University Hospital', 'Albuquerque Clinic',
       'Minneapolis Memorial Hospital', 'Detroit Memorial Hospital',
       'Nashville Regional Hospital', 'Kansas City Medical Center',
       'Boise Memorial Hospital', 'Boulder University Hospital',
       'New Orleans Regional Hospital', 'Cincinnati Health System',
       'Baton Rouge Memorial Hospital', 'Jersey City Regional Hospital',
       'Madison Clinic', 'Boston Community Health Center',
       'Eugene Community Health Center', 'Jacksonville Memorial Hospital',
       'Portland Community Health Center', 'Cleveland Medical Center',
       'Omaha Community Health Center', 'Little Rock General Hospital',
       'Grand Rapids Regional Hospital', 'Little Rock Medical Center',
       'Milwaukee Clinic', 'Fresno University Hospital',
       'Richmond University Hospital', 'Austin Clinic',
       'Miami University Hospital', 'Savannah Medical Center',
       'San Francisco Memorial Hospital', 'Little Rock Memorial Hospital',
       'Detroit University Hospital', 'Wichita Memorial Hospital',
       'Miami Regional Hospital', 'Jacksonville Health System',
       'Des Moines Health System', 'Columbia Clinic',
       'San Francisco Regional Hospital', 'Orlando General Hospital',
       'Seattle Clinic', 'Minneapolis Regional Hospital',
       'Anchorage Clinic', 'Los Angeles General Hospital',
       'Raleigh Clinic', 'Newark University Hospital', 'Detroit Clinic',
       'Raleigh Community Health Center', 'San Jose University Hospital',
       'Houston University Hospital', 'Sacramento Health System',
       'Provo Regional Hospital', 'Honolulu Community Health Center',
       'Indianapolis Clinic', 'Charlotte Medical Center',
       'Raleigh Memorial Hospital', 'San Jose Health System',
       'Cincinnati Regional Hospital', 'Portland Clinic',
       'Birmingham General Hospital', 'Baltimore Health System',
       'Kansas City Regional Hospital'], dtype=object)

In [263]:
hospital['state'] = hospital['state'].str.strip().str.upper()

In [264]:
hospital['state'].unique()

array(['MS', 'VA', 'GA', 'OK', 'NC', 'ID', 'SC', 'MI', 'UT', 'NJ', 'MD',
       'IL', 'NY', 'WI', 'OH', 'NE', 'MO', 'CA', 'CT', 'AL', 'IA', 'FL',
       'TX', 'AK', 'RI', 'HI', 'MN', 'MA', 'AZ', 'CO', 'IN', 'AR', 'KY',
       'PA', 'KS', 'WA', 'NM', 'OR', 'TN', 'LA'], dtype=object)

In [276]:
hospital['accreditation_status'].unique()

array(['Unknown', 'Not Accredited', 'NABH Accredited', 'JCI Accredited',
       'CMS Certified'], dtype=object)

In [271]:
hospital['accreditation_status'] = hospital['accreditation_status'].str.strip().str.title().str.replace(r'\s+', ' ', regex=True)

In [273]:
hospital['accreditation_status'] = hospital['accreditation_status'].str.replace('Nabh Accredited','NABH Accredited')

In [274]:
hospital['accreditation_status'] = hospital['accreditation_status'].str.replace('Jci Accredited','JCI Accredited')

In [275]:
hospital['accreditation_status'] = hospital['accreditation_status'].str.replace('Cms Certified','CMS Certified')

In [277]:
hospital['accreditation_status'].value_counts()

accreditation_status
JCI Accredited     73
Not Accredited     69
CMS Certified      65
NABH Accredited    57
Unknown            36
Name: count, dtype: int64

In [280]:
hospital[['bed_capacity','established_year']].describe()

       bed_capacity  established_year
count    270.000000        300.000000
mean     362.870370       1966.463333
std      296.868103         28.066011
min       50.000000       1920.000000
25%      150.000000       1940.750000
50%      250.000000       1966.000000
75%      500.000000       1991.250000
max     1000.000000       2015.000000

In [281]:
disease.dtypes

disease_id            object
disease_name          object
disease_category      object
icd10_code            object
chronic_flag          object
transmission_type     object
severity_level        object
avg_recovery_days    float64
dtype: object

In [282]:
disease

,disease_id,disease_name,disease_category,icd10_code,chronic_flag,transmission_type,severity_level,avg_recovery_days
0,DIS039,Colorectal Cancer,Oncology,C18,Yes,Non-communicable,Severe,NaN
1,DIS038,lung cancer,Oncology,C34,Yes,Non-communicable,Chronic-Managed,NaN
2,DIS033,Alzheimer's Disease,Neurological,G30,Yes,Non-communicable,Severe,NaN
3,DIS045,Psoriasis,Dermatological,L40,Yes,Non-communicable,Moderate,NaN
4,DIS049,Irritable Bowel Syndrome,Digestive,K58,Yes,Non-communicable,NaN,NaN
5,DIS001,Type 2 Diabetes Mellitus,Metabolic,E11,Yes,Non-communicable,Chronic-Managed,NaN
6,DIS028,OSTEOPOROSIS,Musculoskeletal,M81,Yes,Non-communicable,Chronic-Managed,NaN
7,DIS002,TYPE 1 DIABETES MELLITUS,Metabolic,E10,Yes,Non-communicable,Moderate,NaN
8,DIS024,Measles,Infectious,B05,No,Airborne,Mild,12.0
9,DIS014,Bronchitis,Respiratory,J40,No,Airborne,Mild,17.0
10,DIS010,influenza,Respiratory,J10,No,AIRBORNE,Mild,28.0
11,DIS011,COVID-19,Respiratory,U07.1,No,Airborne,Severe,4.0
12,DIS031,Bipolar Disorder,Mental Health,F31,Yes,NON-COMMUNICABLE,Severe,NaN
13,DIS050,Conjunctivitis,Ophthalmic,H10,No,Contact,Moderate,30.0
14,DIS040,Prostate Cancer,Oncology,C61,Yes,Non-communicable,Severe,NaN
15,DIS018,Hepatitis C,infectious,B17.1,Yes,BLOODBORNE,Moderate,NaN
16,DIS048,Peptic Ulcer Disease,Digestive,K27,Yes,Non-communicable,Moderate,NaN
17,DIS037,Breast Cancer,Oncology,C50,Yes,Non-communicable,Moderate,NaN
18,DIS030,Anxiety Disorder,Mental Health,F41,Yes,Non-Communicable,Chronic-Managed,NaN
19,DIS047,Gastroenteritis,Digestive,A09,No,Foodborne,Moderate,22.0
20,DIS013,Common Cold,Respiratory,J00,No,Airborne,Severe,26.0
21,DIS029,Depression,MENTAL HEALTH,F32,Yes,Non-communicable,Chronic-Managed,NaN
22,DIS037,Breast Cancer,Oncology,C50,Yes,Non-communicable,Moderate,NaN
23,DIS017,Hepatitis B,Infectious,B16,Yes,BLOODBORNE,Moderate,NaN
24,DIS003,Hypertension,Cardiovascular,I10,Yes,Non-communicable,NaN,NaN
25,DIS026,Rheumatoid Arthritis,Musculoskeletal,M06,Yes,Non-communicable,Moderate,NaN
26,DIS020,Malaria,Infectious,B54,No,Vector-borne,Mild,6.0
27,DIS007,ASTHMA,Respiratory,J45,Yes,NON-COMMUNICABLE,Moderate,NaN
28,DIS015,Chronic Kidney Disease,Renal,N18,Yes,Non-communicable,Chronic-Managed,NaN
29,DIS043,Obesity,metabolic,E66,Yes,Non-communicable,NaN,NaN
30,DIS025,Chickenpox,Infectious,B01,No,Airborne,Severe,29.0
31,DIS006,Stroke,cardiovascular,I63,No,Non-communicable,Mild,22.0
32,DIS036,Migraine,Neurological,G43,Yes,Non-communicable,Moderate,NaN
33,DIS034,Parkinson's Disease,Neurological,G20,Yes,Non-communicable,Chronic-Managed,NaN
34,DIS005,Congestive Heart Failure,Cardiovascular,I50,Yes,Non-communicable,Severe,NaN
35,DIS004,Coronary Artery Disease,Cardiovascular,I25,Yes,Non-communicable,Chronic-Managed,NaN
36,DIS021,Dengue Fever,Infectious,A90,No,Vector-borne,Mild,15.0
37,DIS027,Osteoarthritis,Musculoskeletal,M19,Yes,Non-communicable,Chronic-Managed,NaN
38,DIS042,Skin Cancer (Melanoma),Oncology,C43,Yes,Non-communicable,Moderate,NaN
39,DIS022,Typhoid Fever,Infectious,A01,No,Foodborne,Severe,5.0
40,DIS023,Cholera,Infectious,A00,No,Waterborne,Severe,20.0
41,DIS032,Schizophrenia,Mental Health,F20,Yes,Non-communicable,Moderate,NaN
42,DIS035,Epilepsy,Neurological,G40,Yes,Non-communicable,Severe,NaN
43,DIS008,chronic obstructive pulmonary disease,respiratory,J44,Yes,Non-communicable,Moderate,NaN
44,DIS038,lung cancer,Oncology,C34,Yes,Non-communicable,Chronic-Managed,NaN
45,DIS012,Tuberculosis,Respiratory,A15,Yes,Airborne,Chronic-Managed,NaN
46,DIS019,hiv/aids,Infectious,B20,Yes,Bloodborne,Moderate,NaN
47,DIS044,Anemia,Hematological,D64,No,Non-communicable,Moderate,23.0
48,DIS023,Cholera,Infectious,A00,No,Waterborne,Severe,20.0
49,DIS009,Pneumonia,Respiratory,J18,No,airborne,Severe,11.0
50,DIS046,Eczema,Dermatological,L20,Yes,Non-communicable,NaN,NaN
51,DIS016,Acute Kidney Injury,Renal,N17,No,Non-communicable,Moderate,20.0
52,DIS041,Leukemia,Oncology,C95,Yes,Non-communicable,Severe,NaN

In [283]:
clean_col = ['disease_name','disease_category','chronic_flag','transmission_type','severity_level']

for col in clean_col:
    disease[col] = disease[col].str.strip().str.title().str.replace(r'\s+', ' ', regex=True)

In [301]:
disease['disease_name'].unique()
disease['disease_category'].unique()
disease['chronic_flag'].unique()
disease['transmission_type'].unique()
disease['severity_level'].unique()

array(['Severe', 'Chronic-Managed', 'Moderate', nan, 'Mild'], dtype=object)

In [285]:
disease[
    ~disease['disease_id'].str.match(r'^DIS[A-Z0-9]*$', na=False)
]

Empty DataFrame
Columns: [disease_id, disease_name, disease_category, icd10_code, chronic_flag, transmission_type, severity_level, avg_recovery_days]
Index: []

In [286]:
disease['disease_name'] = disease['disease_name'].str.replace("Alzheimer'S Disease","Alzheimer's Disease")

In [287]:
disease['disease_name'] = disease['disease_name'].str.replace("Parkinson'S Disease","Parkinson's Disease")

In [288]:
disease['disease_name'] = disease['disease_name'].str.replace('Hiv/Aids','HIV/AIDS')

In [298]:
disease['transmission_type'] = disease['transmission_type'].str.replace('Airborne','Air-Borne')
disease['transmission_type'] = disease['transmission_type'].str.replace('Bloodborne','Blood-Borne')
disease['transmission_type'] = disease['transmission_type'].str.replace('Foodborne','Food-Borne')
disease['transmission_type'] = disease['transmission_type'].str.replace('Waterborne','Water-Borne')

In [300]:
disease['transmission_type'].value_counts()

transmission_type
Non-Communicable    35
Air-Borne            8
Blood-Borne          3
Food-Borne           2
Vector-Borne         2
Water-Borne          2
Contact              1
Name: count, dtype: int64

In [319]:
disease.isna().sum()

disease_id           0
disease_name         0
disease_category     0
icd10_code           0
chronic_flag         0
transmission_type    0
severity_level       0
avg_recovery_days    0
dtype: int64

In [303]:
disease['severity_level'] = disease['severity_level'].fillna('Unknown')

In [310]:
disease['avg_recovery_days'] = disease['avg_recovery_days'].fillna(disease['avg_recovery_days'].median())

In [312]:
disease.head(10)

,disease_id,disease_name,disease_category,icd10_code,chronic_flag,transmission_type,severity_level,avg_recovery_days
0,DIS039,Colorectal Cancer,Oncology,C18,Yes,Non-Communicable,Severe,20.0
1,DIS038,Lung Cancer,Oncology,C34,Yes,Non-Communicable,Chronic-Managed,20.0
2,DIS033,Alzheimer's Disease,Neurological,G30,Yes,Non-Communicable,Severe,20.0
3,DIS045,Psoriasis,Dermatological,L40,Yes,Non-Communicable,Moderate,20.0
4,DIS049,Irritable Bowel Syndrome,Digestive,K58,Yes,Non-Communicable,Unknown,20.0
5,DIS001,Type 2 Diabetes Mellitus,Metabolic,E11,Yes,Non-Communicable,Chronic-Managed,20.0
6,DIS028,Osteoporosis,Musculoskeletal,M81,Yes,Non-Communicable,Chronic-Managed,20.0
7,DIS002,Type 1 Diabetes Mellitus,Metabolic,E10,Yes,Non-Communicable,Moderate,20.0
8,DIS024,Measles,Infectious,B05,No,Air-Borne,Mild,12.0
9,DIS014,Bronchitis,Respiratory,J40,No,Air-Borne,Mild,17.0

In [313]:
disease['icd10_code'] = disease['icd10_code'].str.strip().str.upper()

In [314]:
disease['icd10_code'].value_counts()

icd10_code
C34      2
C50      2
A00      2
M19      1
N18      1
E66      1
B01      1
I63      1
G43      1
G20      1
I50      1
I25      1
A90      1
C18      1
J45      1
A01      1
F20      1
G40      1
J44      1
A15      1
B20      1
D64      1
J18      1
L20      1
N17      1
C43      1
B54      1
M06      1
U07.1    1
G30      1
L40      1
K58      1
E11      1
M81      1
E10      1
B05      1
J40      1
J10      1
F31      1
I10      1
H10      1
C61      1
B17.1    1
K27      1
F41      1
A09      1
J00      1
F32      1
B16      1
C95      1
Name: count, dtype: int64

In [315]:
disease.duplicated().sum()

np.int64(3)

In [316]:
# Before dropping duplicates
disease.shape

(53, 8)

In [317]:
disease = disease.drop_duplicates(subset='disease_id',keep='first')

In [318]:
# After dropping duplicates
disease.shape

(50, 8)

In [320]:
date.head()

,date_id,full_date,day,month,month_name,quarter,year,day_of_week,is_weekend,fiscal_year
0,20221017,2022-10-17,17.0,10,October,Q4,2022,Monday,False,FY2023
1,20230130,2023-01-30,30.0,1,January,Q1,2023,Monday,False,fy2023
2,20241107,2024-11-07,7.0,11,november,q4,2024,Thursday,False,FY2025
3,20230816,2023-08-16,16.0,8,August,Q3,2023,Wednesday,False,FY2024
4,20220329,2022-03-29,29.0,3,March,Q1,2022,Tuesday,False,FY2022

In [326]:
date.dtypes

date_id                 int64
full_date      datetime64[ns]
day                   float64
month                   int64
month_name             object
quarter                object
year                    int64
day_of_week            object
is_weekend             object
fiscal_year            object
dtype: object

In [325]:
date['full_date'] = pd.to_datetime(date['full_date'],errors='coerce')

In [332]:
date.isna().sum()

date_id          0
full_date        0
day              0
month            0
month_name       0
quarter          0
year             0
day_of_week      0
is_weekend     201
fiscal_year      0
dtype: int64

In [323]:
date[date['day'].isna()]

,date_id,full_date,day,month,month_name,quarter,year,day_of_week,is_weekend,fiscal_year
11,20210329,2021-03-29,NaN,3,March,Q1,2021,monday,False,FY2021
67,20240108,2024-01-08,NaN,1,JANUARY,Q1,2024,Monday,False,FY2024
68,20240410,2024-04-10,NaN,4,APRIL,Q2,2024,Wednesday,False,Fy2025
79,20220622,2022-06-22,NaN,6,June,Q2,2022,Wednesday,False,FY2023
100,20221013,2022-10-13,NaN,10,october,Q4,2022,Thursday,False,FY2023
...,...,...,...,...,...,...,...,...,...,...
1784,20220407,2022-04-07,NaN,4,April,Q2,2022,Thursday,False,FY2023
1803,20241213,2024-12-13,NaN,12,December,Q4,2024,Friday,False,FY2025
1804,20240805,2024-08-05,NaN,8,August,Q3,2024,Monday,False,FY2025
1848,20220926,2022-09-26,NaN,9,september,Q3,2022,Monday,False,fy2023
1887,20240923,2024-09-23,NaN,9,September,Q3,2024,Monday,False,FY2025

In [327]:
date['day'] = date['day'].fillna(date['full_date'].dt.day)

In [330]:
date['day'] = pd.to_numeric(date['day'],errors='coerce').astype('int')

In [331]:
date[date['date_id'] == 20210329]

,date_id,full_date,day,month,month_name,quarter,year,day_of_week,is_weekend,fiscal_year
11,20210329,2021-03-29,29,3,March,Q1,2021,monday,False,FY2021

In [344]:
date[date['is_weekend'].isna()]

Empty DataFrame
Columns: [date_id, full_date, day, month, month_name, quarter, year, day_of_week, is_weekend, fiscal_year]
Index: []

In [341]:
cleancol = ['month_name','day_of_week']
for col in cleancol:
    date[col] = date[col].str.strip().str.title()

In [342]:
mask = date['is_weekend'].isna()

date.loc[mask, 'is_weekend'] = (
    date.loc[mask, 'day_of_week'].isin(['Saturday', 'Sunday'])
)

In [345]:
date['day_of_week'] = (
    date['day_of_week']
    .astype('string')
    .str.strip()
    .str.title()
)

In [358]:
date[date['date_id'] == 20220502]
date[date['date_id'] == 20210522]
date[date['date_id'] == 20220717]

,date_id,full_date,day,month,month_name,quarter,year,day_of_week,is_weekend,fiscal_year
270,20220717,2022-07-17,17,7,July,Q3,2022,Sunday,True,FY2023
1044,20220717,2022-07-17,17,7,July,Q3,2022,Sunday,True,FY2023
1871,20220717,2022-07-17,17,7,July,Q3,2022,Sunday,True,FY2023

In [355]:
date['is_weekend'] = date['day_of_week'].isin(
    ['Saturday', 'Sunday']
)

In [356]:
date[date['day_of_week'] == 'Sunday'][['day_of_week', 'is_weekend']]

     day_of_week  is_weekend
6         Sunday        True
13        Sunday        True
26        Sunday        True
29        Sunday        True
41        Sunday        True
...          ...         ...
1856      Sunday        True
1861      Sunday        True
1871      Sunday        True
1892      Sunday        True
1894      Sunday        True

[287 rows x 2 columns]

In [361]:
date['month_name'].unique()
date['quarter'].unique()
date['day_of_week'].unique()
date['is_weekend'].unique()
date['fiscal_year'].unique()

array(['FY2023', 'FY2025', 'FY2024', 'FY2022', 'FY2021'], dtype=object)

In [350]:
date['quarter'] = date['quarter'].str.strip().str.upper()

In [357]:
date['is_weekend'].value_counts()

is_weekend
False    1342
True      557
Name: count, dtype: int64

In [360]:
date['fiscal_year'] = date['fiscal_year'].str.strip().str.upper()

## 3. Save files(csv)

In [362]:
patient.to_csv('Dim_Patient.csv', index=False)
location.to_csv('Dim_Location.csv', index=False)
hospital.to_csv('Dim_Hospital.csv', index=False)
disease.to_csv('Dim_Disease.csv', index=False)
date.to_csv('Dim_Date.csv', index=False)
fact_disease_incident.to_csv('Fact_Disease_Incident.csv', index=False)